/* Generated from the frontend's current visible strings. Keep technical identifiers in the source text. */
export const viTextMap: Readonly<Record<string, string>> = {
  " · 失败 ": "Thất bại",
  " · 成功 ": "thành công",
  " · 提链 ": "· Chainlifting",
  " · 无效 ": "không có hiệu quả",
  " · 更新 ": "Cập nhật",
  " · 进度：": "Tiến độ",
  " · 进行中 ": "Đang tiến hành",
  " 个账号": "tài khoản",
  " 个运行中": "đang chạy",
  " 条": "đường",
  " 至 ": "Đến ngày",
  " 项": "Hạng mục",
  "+6281234567890----https://example.com/sms/123\n每行一个号码": "+6281234567890---- https://example.com/sms/123\nMột số trên mỗi dòng",
  "+手机号----https://接码链接": "+ Số điện thoại ---- https://lien-ket-nhan-ma",
  "2Captcha 超时（秒）": "Thời gian chờ 2 Captcha (giây)",
  "2Captcha 轮询（秒）": "2Captcha Polling (giây)",
  "2FA 密钥": "Khóa 2FA",
  "4-6 位": "# 4- # 6",
  "6 位数字": "6 chữ số",
  "API 地址": "Địa chỉ API",
  "API 密钥 Token": "Mã thông báo khóa API",
  "AT 列表已清空": "Danh sách AT trống",
  "AT 状态": "Trạng thái AT",
  "AT定时检测": "Tại thời điểm phát hiện thời gian",
  "AT无效或已过期": "Không hợp lệ hoặc hết hạn lúc",
  "AT检测": "Phát hiện AT",
  "AT检测失败": "Phát hiện AT không thành công",
  "AT检测失败：{error}": "Phát hiện không thành công: {error}",
  "AT检测完成：有效 {valid} 个，无效 {invalid} 个，检测失败 {failed} 个；已对无效账户启动续期": "Khi phát hiện xong: {valid} hợp lệ, {invalid} không hợp lệ, không thành công {failed}; bắt đầu gia hạn cho tài khoản không hợp lệ",
  "AT检测完成：有效 {valid} 个，无效 {invalid} 个，跳过 {skipped} 个，检测失败 {failed} 个": "Khi phát hiện xong: hợp lệ {valid}, không hợp lệ {invalid}, bỏ qua {skipped}, không thành công {failed}",
  "AT检测完成：有效 {valid} 个，无效 {invalid} 个，跳过 {skipped} 个，检测失败 {failed} 个；已对无效账户启动续期": "Khi phát hiện xong: {valid} hợp lệ, {invalid} không hợp lệ, bỏ qua {skipped}, không thành công {failed}; bắt đầu gia hạn vì tài khoản không hợp lệ",
  "AT检测被上游拦截，未确认令牌失效，请稍后重试": "Phát hiện AT bị chặn ngược dòng, mã thông báo chưa được xác nhận không hợp lệ, vui lòng thử lại sau",
  "AT检测进度": "Tiến độ phát hiện AT",
  "AT续期": "AT Gia hạn",
  "AT续期失败": "Tại thời điểm gia hạn không thành công",
  "AT续期进度": "Tiến độ gia hạn AT",
  "AT过期时间": "AT Thời gian hết hạn",
  "Approve 跳转": "Phê duyệt JUMP",
  "BA 链接": "BA link",
  "Buyer 模式": "Chế độ người mua",
  "CPF / CNPJ 交替": "Thay thế CPF/CNPJ",
  "ChatGPT 密码": "Mật khẩu ChatGPT",
  "ChatGPT 注册/登录已经完成，但手机号阶段无法继续；已保存 Session 并保留已注册状态": "Đăng ký/đăng nhập ChatGPT đã hoàn tất, nhưng giai đoạn số điện thoại không thể tiếp tục; Phiên đã được lưu và trạng thái đăng ký được giữ nguyên",
  "ChatGPT 账户注册流量 / 邮箱账户历史代理交互总流量": "Đăng ký tài khoản ChatGPT Lưu lượng truy cập/Hộp thư Lịch sử tài khoản Tương tác proxy Tổng lưu lượng truy cập",
  "ChatGPT 账户注册流量 / 邮箱账户历史代理交互总流量（HTTP 应用层估算，不含 TLS/TCP；缓存回放不计）": "Lưu lượng đăng ký tài khoản ChatGPT/lưu lượng tương tác tác tác nhân lịch sử tài khoản hộp thư (ước tính lớp ứng dụng http, không bao gồm TLS/TCP; phát lại bộ nhớ cache không được tính)",
  "Checkout 代理池": "Thanh toán Proxy Pool",
  "Checkout 代理池 · VN": "Checkout Proxy Pool · VN",
  "Checkout 代理池和 Promotion 代理池都必须填写": "Checkout Proxy Pool và Promotion Proxy Pool đều được yêu cầu",
  "Checkout 探测完成：检测成功 {detected} 个，重试 {retried} 个，跳过 {skipped} 个，失败 {failed} 个": "Đã hoàn tất phát hiện thanh toán: {detected} được phát hiện, {retried} được thử lại, {skipped} bị bỏ qua, {failed} không thành công",
  "Checkout 类型": "Loại trả phòng",
  "Checkout 类型筛选": "Bộ lọc loại trả phòng",
  "Checkout探测": "Phát hiện trả phòng",
  "Checkout检测": "Phát hiện thanh toán",
  "Checkout进度": "Tiến độ trả phòng",
  "Checkout链接": "Liên kết trả phòng",
  "CloudMail API 地址": "Địa chỉ API CloudMail",
  "CloudMail 站点密码（PASSWORDS）": "Mật khẩu trang web CloudMail (mật khẩu)",
  "Codex 空间": "Dấu cách Codex",
  "Codex 空间名称": "Tên khoảng trắng Codex",
  "Codex接码绑定": "Gắn kết Codex",
  "FireFox 临时号码平台。使用 API 密钥 Token 直接取号，每 5 秒轮询验证码，不可用号码将在 35 秒后自动释放。": "Nền tảng số tạm thời FireFox. Sử dụng Mã thông báo khóa API để lấy số trực tiếp, thăm dò mã xác minh cứ sau 5 giây và số không khả dụng sẽ được tự động phát hành sau 35 giây.",
  "FireFox 单号最高价格必须大于 0": "Giá tối đa của số đơn hàng FireFox phải lớn hơn 0",
  "FireFox 已配置": "Đã định cấu hình FireFox",
  "FireFox 接码供应商": "Nhà cung cấp FireFox Patch",
  "FireFox 配置已保存": "Đã lưu cấu hình FireFox",
  "GCash 必须填写 PH Checkout 代理池": "GCash phải lấp đầy nhóm proxy của PH Checkout",
  "GCash 每次尝试选用一个 PH 代理，并复用同一会话完成 Checkout、taxes、confirm 与 start。": "GCash sử dụng một proxy PH mỗi lần thử và ghép kênh cùng một phiên để hoàn thành Thanh toán, tính thuế, xác nhận và bắt đầu.",
  "GoPay 功能": "Tính năng GoPay",
  "GoPay 实时概览": "Tổng quan về GoPay Live",
  "GoPay 支付": "Thanh toán bằng GoPay",
  "GoPay 数据加载失败": "Không thể tải dữ liệu GoPay",
  "GoPay 数据已刷新": "Đã làm mới dữ liệu GoPay",
  "GoPay 账号": "Tài khoản GoPay",
  "Google 邮箱功能未启用，请先启用对应的邮箱功能": "Google Mail chưa được bật, vui lòng bật hộp thư tương ứng trước",
  "LS 添加完成：成功 {success} 个，跳过 {skipped} 个，部分完成 {partial} 个，失败 {failed} 个": "LS đã thêm thành công: {success}, đã bỏ qua {skipped}, đã hoàn thành một phần {partial}, không thành công {failed}",
  "LubanSMS 接码供应商": "Nhà cung cấp Đầu nối LubanSMS",
  "LubanSMS 连接正常": "Kết nối LubanSMS OK",
  "LubanSMS 配置已保存": "Đã lưu cấu hình LubanSMS",
  "MOMO Access Token 列表": "Danh sách mã thông báo truy cập Momo",
  "MOMO 任务不存在或已被清理": "Nhiệm vụ Momo không tồn tại hoặc đã được dọn dẹp",
  "MOMO 任务创建失败": "Tạo tác vụ Momo không thành công",
  "MOMO 任务概览": "Tổng quan nhiệm vụ Momo",
  "MOMO 任务状态已刷新": "Đã làm mới trạng thái tác vụ Momo",
  "MOMO 任务状态连续读取失败，可放弃恢复后重新提交": "Đọc liên tục trạng thái tác vụ Momo không thành công, có thể loại bỏ phục hồi và gửi lại",
  "MOMO 任务进度": "Tiến trình tác vụ Momo",
  "MOMO 协议支付": "Thanh toán theo Thỏa thuận Momo",
  "MOMO 协议支付任务已提交": "Đã gửi nhiệm vụ thanh toán thỏa thuận Momo",
  "MOMO 批量任务进度": "Tiến độ nhiệm vụ hàng loạt Momo",
  "MOMO 授权链接": "Liên kết ủy quyền Momo",
  "MOMO 授权链接已复制": "Đã sao chép liên kết ủy quyền Momo",
  "MOMO 授权链接已生成": "Đã tạo liên kết ủy quyền Momo",
  "MOMO 提链失败": "Liên kết chuỗi Momo không thành công",
  "MOMO 支付": "Thanh toán Momo",
  "MOMO 账户任务 · ": "Tác vụ tài khoản Momo ·",
  "MOMO 账户任务结果": "Kết quả tác vụ tài khoản Momo",
  "Microsoft 邮箱功能未启用，请先启用对应的邮箱功能": "Tính năng hộp thư của Microsoft chưa được bật, vui lòng bật tính năng hộp thư tương ứng trước",
  "Midtrans Alibaba 人机验证": "Xác minh máy con người của Midtrans Alibaba",
  "Midtrans 链接": "Midtrans Link",
  "PH Checkout 代理池": "PH Checkout Proxy Pool",
  "PIN 修改任务仍在执行，请稍后刷新账号状态": "Tác vụ sửa đổi mã PIN vẫn đang chạy, vui lòng làm mới trạng thái tài khoản sau",
  "PIN 修改失败": "Không thể thay đổi mã PIN",
  "PIN 修改成功": "Đã thay đổi mã PIN thành công",
  "PIN 必须是 6 位数字": "Mã PIN phải có 6 chữ số",
  "PIN 状态": "Trạng thái mã PIN",
  "PIN 状态已刷新": "Đã làm mới trạng thái mã PIN",
  "PIN 结果不确定": "Kết quả mã PIN không chắc chắn",
  "PLUS试用中": "Đang dùng thử Plus",
  "PayPal BA 链接或 Token": "Liên kết hoặc mã thông báo PayPal BA",
  "PayPal 任务已取消": "Nhiệm vụ PayPal đã bị hủy",
  "PayPal 协议任务已创建": "Đã tạo tác vụ thỏa thuận PayPal",
  "PayPal 协议支付": "Thanh toán thỏa thuận PayPal",
  "PayPal 支付": "Thanh toán qua PayPal",
  "PayPal 配置已保存": "Đã lưu cấu hình PayPal",
  "PayPal 验证码已提交": "Đã gửi mã xác minh PayPal",
  "PaymentMethod 创建失败": "Tạo phương thức thanh toán không thành công",
  "Plus 优惠活动": "Cộng với các chương trình khuyến",
  "Promotion 代理池 ": "Quỹ Proxy khuyến mãi",
  "Promotion 代理池 · VN": "Quỹ Proxy khuyến mãi · VN",
  "Promotion 国家 / 地区": "Quốc gia áp dụng khuyến mãi",
  "Refresh Token 已就绪": "Đã sẵn sàng làm mới mã thông báo",
  "Refresh Token 续期不可用，切换登录流程": "Làm mới quy trình gia hạn mã thông báo không khả dụng, chuyển đổi quy trình đăng nhập",
  "Remail 将按并发槽位逐个下单，总下单量为 {count}": "Remail sẽ được sắp xếp từng cái một theo các vị trí đồng thời, với tổng khối lượng đặt hàng là {count}",
  "Remail 第三方邮箱供应商": "Gửi lại nhà cung cấp hộp thư của bên thứ ba",
  "Remail邮箱": "Email chuyển tiếp",
  "SMSBower 已配置": "Đã định cấu hình SMSBower",
  "SMSBower 接码供应商": "Nhà cung cấp mã bản vá SMSBower",
  "SMSBower 配置已保存": "Đã lưu cấu hình SMSBower",
  "SMSPool 临时号码平台，可在自建手机号池和 SMSBower 不可用时自动购买一次性接码号码。": "Nền tảng số tạm thời SMSPool, tự động mua số truy cập một lần khi không có sẵn nhóm điện thoại tự xây dựng và SMSBower.",
  "SMSPool 已配置": "SMSPool được định cấu hình",
  "SMSPool 接码供应商": "Nhà cung cấp dịch vụ nhận SMSPool",
  "SMSPool 配置已保存": "Đã lưu cấu hình SMSPool",
  "Sentinel 协议运行时": "Thời gian chạy giao thức Sentinel",
  "Solverify 超时（秒）": "Giải quyết hết thời gian chờ (giây)",
  "Solverify 轮询（秒）": "Giải quyết Bỏ phiếu (giây)",
  "Stripe 安全卡片组件尚未加载": "Thành phần thẻ an toàn Stripe chưa được tải",
  "Stripe 安全组件加载失败，请检查浏览器网络或拦截扩展后重试": "Không thể tải thành phần bảo mật Stripe, vui lòng kiểm tra mạng trình duyệt của bạn hoặc chặn tiện ích mở rộng và thử lại",
  "Stripe 安全组件加载超时，请检查浏览器网络或拦截扩展后重试": "Đã hết thời gian tải thành phần bảo mật Stripe, vui lòng kiểm tra mạng trình duyệt của bạn hoặc chặn tiện ích mở rộng và thử lại",
  "Stripe 安全组件脚本已返回，但组件没有初始化": "Tập lệnh thành phần bảo mật Stripe được trả về, nhưng thành phần không được khởi tạo",
  "Stripe 已连接": "Đã kết nối Stripe",
  "SunnyRegister Worker 已接收注册任务": "SunnyRegister Worker đã nhận được một nhiệm vụ đăng ký",
  "SunnyRegister 注册机控制台": "Bảng điều khiển đăng ký SunnyRegister",
  "TR · 土耳其": "TR · Thổ Nhĩ Kỳ",
  "Token预览": "Xem trước mã thông báo",
  "URL API 邮件浏览器": "Trình duyệt thư API URL",
  "US Checkout / TR 优惠": "Giảm giá Trả phòng/TR tại Hoa Kỳ",
  "domain邮箱": "email tên miền",
  "email----ChatGPT密码----https://收码URL----2FA密钥（后3段均可选）": "email ---- Mật khẩu ChatGPT ---- https://URL-nhan-ma ---- Khóa 2FA (3 phần cuối là tùy chọn)",
  "email----serviceToken / 凭证": "email----serviceToken/Thông tin xác thực",
  "email----域名邮箱凭证 JSON": "email ---- Thông tin đăng nhập email miền JSON",
  "iDEAL 银行": "ngân hàng iDEAL",
  "sub2api 已配置": "sub2api được định cấu hình",
  "sub2api 未完整配置": "sub2api chưa được định cấu hình đầy đủ",
  "上一页": "Trang trước",
  "上次检测": "Kiểm tra lần cuối",
  "上游未提供免登录二维码": "Không có mã QR không đăng nhập được cung cấp ngược dòng",
  "下一页": "Trang kế",
  "下载二维码": "Tải xuống mã QR",
  "不使用远端代理": "Không sử dụng proxy từ xa",
  "不可用": "không chọn",
  "不可自动接码": "Không tự động chấp nhận",
  "不用于接码": "Không được sử dụng để nhận mã",
  "不选择任何用途时，该代理即使启用也不会被任何任务使用。": "Khi không sử dụng được chọn, tác nhân sẽ không được sử dụng bởi bất kỳ tác vụ nào ngay cả khi được bật.",
  "专业计划": "Kế hoạch chuyên nghiệp",
  "两个大写国家代码，例如 US / JP / BR": "Hai mã quốc gia viết hoa, ví dụ: US/JP/BR",
  "个人订阅": "Đăng ký cá nhân",
  "中国": "China",
  "中国台湾": "Đài Loan",
  "中国香港": "Hồng Kông",
  "丹麦": "Đan Mạch",
  "为已注册 ChatGPT 账户批量提取支付链接、跳转地址和支付二维码。": "Rút hàng loạt các liên kết thanh toán, địa chỉ JUMP và mã QR thanh toán cho các tài khoản ChatGPT đã đăng ký.",
  "主要生成 CPF": "CPF được tạo ban đầu",
  "主题": "Sắc thái",
  "乌克兰": "Ukraine",
  "乌拉圭": "Uruguay",
  "二维码已过期": "Mã QR đã hết hạn",
  "交易待核对": "Giao dịch đang chờ xem xét",
  "人机验证": "Xác minh giữa người và máy tính",
  "人机验证配置已保存": "Đã lưu cấu hình xác thực người-máy",
  "仅公共资源": "Chỉ tài nguyên công cộng",
  "仅已注册且套餐为 free 的账户支持 Checkout 探测": "Phát hiện thanh toán chỉ được hỗ trợ cho các tài khoản đã đăng ký với gói miễn phí",
  "仅已注册且套餐为 free 的账户支持试用检测": "Phát hiện dùng thử chỉ được hỗ trợ cho các tài khoản đã đăng ký với gói miễn phí",
  "仅提链": "Chỉ nâng xích",
  "仅支持已知原 PIN 的账号；忘记 PIN 请使用 GoPay 官方找回流程。": "Chỉ hỗ trợ các tài khoản có mã PIN gốc đã biết; nếu bạn quên mã PIN, vui lòng sử dụng quy trình truy xuất GoPay chính thức.",
  "仅注册 ChatGPT": "Chỉ đăng ký ChatGPT",
  "仅生成 CNPJ": "Chỉ tạo CNPJ",
  "仅适用于已知原 PIN 的账号": "Chỉ áp dụng cho các tài khoản có mã PIN gốc đã biết",
  "从文件导入": "Nhập từ tệp",
  "从注册与登录或支付中心创建任务": "Tạo Nhiệm vụ từ Đăng ký & Đăng nhập hoặc Trung tâm Thanh toán",
  "付款 PIN（可选）": "Mã PIN thanh toán (không bắt buộc)",
  "代理": "Ủy nhiệm:",
  "代理与出口准备完成": "Chuẩn bị đại lý và xuất khẩu đã hoàn thành",
  "代理与网络出口准备完成": "Hoàn tất chuẩn bị xuất tác nhân và mạng",
  "代理关闭": "Nhân viên chăm sóc khách hàng",
  "代理出口设置已更新": "Đã cập nhật cài đặt cửa hàng ủy quyền",
  "代理地址": "Địa chỉ người được ủy quyền",
  "代理开启": "Bật ủy quyền",
  "代理检测完成": "Hoàn tất kiểm tra proxy",
  "代理池": "Proxy Pool",
  "代理池（可选）": "Proxy pool (không bắt buộc)",
  "代理配置": "Cấu hình proxy",
  "代理（可选）": "Proxy (không bắt buộc)",
  "以色列": "Du lịch",
  "任务 ID": "ID tác vụ",
  "任务刷新失败": "Làm mới tác vụ không thành công",
  "任务处理中": "Nhiệm vụ đang thực hiện",
  "任务失败": "Nhiệm vụ thất bại",
  "任务完成": "\"nhiệm vụ hoàn thành…\"",
  "任务已停止": "Tác vụ đã dừng",
  "任务已由用户中断": "Tác vụ bị gián đoạn bởi người dùng",
  "任务已由用户停止": "Người dùng đã dừng tác vụ",
  "任务已结束，请查看账户结果": "Tác vụ đã kết thúc, vui lòng kiểm tra kết quả tài khoản của bạn",
  "任务开始后显示协议执行日志": "Hiển thị nhật ký thực thi giao thức sau khi tác vụ bắt đầu",
  "任务总数": "Tổng số nhiệm vụ",
  "任务恢复异常": "Ngoại lệ khôi phục tác vụ",
  "任务执行失败": "Thực thi tác vụ không thành công",
  "任务日志": "Nhật ký tác vụ",
  "任务未返回支付链接": "Tác vụ không trả về liên kết thanh toán",
  "任务模式": "Chế độ tác vụ",
  "任务状态读取失败": "Đọc trạng thái tác vụ không thành công",
  "任务状态轮询时间较长，仍将继续等待；可使用停止按钮中断任务": "Việc thăm dò trạng thái tác vụ mất nhiều thời gian và sẽ tiếp tục chờ đợi; sử dụng nút dừng để làm gián đoạn tác vụ",
  "任务状态轮询暂时失败，将继续等待任务状态：{error}": "Cuộc thăm dò trạng thái tác vụ tạm thời không thành công, sẽ tiếp tục chờ trạng thái tác vụ: {error}",
  "任务状态连接已恢复，继续跟踪后台任务": "Đã khôi phục kết nối trạng thái tác vụ, tiếp tục theo dõi tác vụ nền",
  "任务状态连接暂时中断，后台任务不受影响，正在自动重连": "Kết nối trạng thái tác vụ tạm thời bị gián đoạn, tác vụ nền không bị ảnh hưởng, tự động kết nối lại",
  "任务详情": "Chi tiết Nhiệm vụ",
  "任务详情、日志和 OTP 输入会显示在这里": "Chi tiết nhiệm vụ, nhật ký và đầu vào OTP sẽ xuất hiện ở đây",
  "任务轮询超时": "Hết thời gian bỏ phiếu nhiệm vụ",
  "任务配置": "Cấu hình tác vụ",
  "优先级": "sự ưu tiên",
  "优先通过 HTTP/TLS 完成注册或登录；后续接码/OAuth 阶段需要页面流程时，仅由后台无头浏览器接管续段。": "Ưu tiên đăng ký hoặc đăng nhập thông qua HTTP/TLS; khi quy trình trang được yêu cầu cho giai đoạn mã kết nối/OAuth tiếp theo, chỉ trình duyệt không có đầu nền mới tiếp quản việc tiếp tục.",
  "优惠码（Team）": "Mã khuyến mãi (Nhóm)",
  "优惠配置": "Cấu hình ưu đãi",
  "会打开浏览器窗口，适合排查人机验证或页面异常": "sẽ mở một cửa sổ trình duyệt phù hợp để khắc phục sự cố xác thực giữa người và máy tính hoặc sự bất thường của trang",
  "低价空间": "Chỗ ở giá rẻ",
  "余额": "Số dư tiền",
  "余额 ": "Số dư tiền",
  "余额、PIN 与登录状态": "Trạng thái số dư, mã PIN và trạng thái đăng nhập",
  "余额、PIN、登录与短信激活状态": "Trạng thái kích hoạt số dư, mã PIN, đăng nhập và SMS",
  "余额已刷新": "Đã làm mới số dư",
  "余额：{balance}": "Số dư: {balance}",
  "使用 Remail 第三方邮箱供应商下单并通过 API 收取验证码": "Đặt hàng với nhà cung cấp email bên thứ ba Remail và nhận mã xác minh qua API",
  "使用0元优惠": "Áp dụng giảm giá $ 0",
  "使用服务器系统网络出口": "Sử dụng lối ra mạng hệ thống máy chủ",
  "使用系统 AT": "SỬ dụng HỆ thống tại",
  "使用自建域名邮箱池生成邮箱并通过 API 收取验证码": "Tạo email bằng cách sử dụng nhóm hộp thư miền tự xây dựng và nhận mã xác minh qua API",
  "使用自建手机号池": "Sử dụng nhóm số điện thoại tự xây dựng",
  "使用自建邮箱池": "Sử dụng nhóm hộp thư tự xây dựng",
  "使用自建邮箱池注册/登录 GPT 账户，并统一管理账户状态、Session、RT 和日志。": "Đăng ký/đăng nhập vào tài khoản GPT của bạn bằng nhóm hộp thư tự xây dựng và quản lý trạng thái tài khoản, Phiên, RT và nhật ký ở một nơi.",
  "使用邮箱池自动收取验证码并完成注册": "Sử dụng nhóm email để tự động thu thập mã xác minh và hoàn tất đăng ký",
  "例如 0.01": "ví dụ: 0,01",
  "例如 US / HK / JP / Brazil": "ví dụ: US/HK/JP/Brazil",
  "供应商编号": "Số nhà cung cấp",
  "供给策略": "Chiến lược cung ứng",
  "保加利亚": "Bulgaria",
  "保存": "Lưu",
  "保存 ChatGPT Session": "Lưu phiên ChatGPT",
  "保存 Remail 配置": "Lưu cấu hình lưu lại",
  "保存人机验证配置": "Lưu cấu hình xác minh người-máy",
  "保存域名邮箱配置": "Lưu cấu hình email miền",
  "保存的 MOMO 任务标识无效，已停止恢复": "Mã định danh tác vụ momo đã lưu không hợp lệ, đã dừng khôi phục",
  "保存设置": "Lưu cài đặt",
  "保存配置": "Lưu cấu hình",
  "保留失败域名邮箱": "Đặt trước email tên miền không thành công",
  "信息": "thông tin",
  "修改 GoPay PIN": "Thay đổi mã PIN GoPay",
  "修改 PIN": "Thay đổi mã PIN",
  "停止": "Dừng Lại",
  "停止中": "Không hoạt động",
  "停止中...": "Đang dừng...",
  "停止任务失败": "Không thể dừng tác vụ",
  "停止当前所有正在执行或等待执行的 AT 续期任务": "Dừng tất CẢ các nhiệm VỤ gia hạn hiện đang được tiến hành hoặc đang chờ thực hiện",
  "停止提链": "Dừng xích nâng",
  "停止整批注册任务，包括提交、排队、Worker 启动和邮箱执行阶段。": "Dừng các nhiệm vụ ghi danh hàng loạt, bao gồm các giai đoạn gửi, xếp hàng, bắt đầu của người lao động và thực hiện hộp thư.",
  "停止续期": "Dừng gia hạn",
  "停止续期任务失败": "Không thể dừng gia hạn tác vụ",
  "停用": "Hủy kích hoạt",
  "克罗地亚": "Croatia",
  "全局日志": "Nhật ký chung",
  "全流程使用代理池": "Sử dụng nhóm proxy trong suốt quá trình",
  "全选": "chọn tất cả",
  "全部": "Tất cả",
  "全部 Checkout": "Tất cả Thanh toán",
  "全部信息": "Tất cả thông tin",
  "全部分组": "Nhóm tất cả",
  "全部国家": "Tất cả các quốc gia",
  "全部套餐": "Tất cả các gói",
  "全部支付方式": "Tất cả các phương thức thanh toán",
  "全部模块": "Tất cả các mô-đun",
  "全部次数": "Mọi lúc",
  "全部清空": "Xóa tất cả",
  "全部状态": "Tất cả trạng thái",
  "全部用途": "Tất cả công dụng",
  "全部试用资格": "Tất cả các điều kiện thử việc",
  "关闭": "Đóng",
  "关闭后，注册或换绑失败时会同时删除 CloudMail 和本项目中的本次邮箱": "Khi đóng, cả CloudMail và email này trong dự án này sẽ bị xóa khi đăng ký hoặc hoán đổi không thành công",
  "关闭后，注册机不会从自建手机号池分配号码；后续可切换为外部接码平台。": "Sau khi tắt, keygen sẽ không chỉ định các số từ nhóm số điện thoại tự xây dựng; nó có thể được chuyển sang một nền tảng truy cập bên ngoài trong tương lai.",
  "关闭后，注册机不会从自建邮箱池分配邮箱。": "Khi tắt, máy ghi danh không chỉ định hộp thư từ nhóm hộp thư tự xây dựng.",
  "关闭添加 LS 进度": "Đóng thêm tiến trình LS",
  "关闭续期进度": "Đóng tiến độ gia hạn",
  "关闭自建域名邮箱池": "Đóng nhóm hộp thư miền tự xây dựng",
  "关闭详情": "Đóng thông tin chi tiết",
  "冰岛": "Băng đảo",
  "准备开始": "Hãy sẵn sàng để bắt đầu",
  "准备续期任务": "Sẵn sàng làm mới nhiệm vụ",
  "分组": "Nhóm% 1",
  "分组筛选": "Bộ lọc nhóm",
  "分配中": "Đang chỉ định",
  "分配手机号并开始接码": "Chỉ định số điện thoại và bắt đầu chấp nhận mã",
  "切换到中文": "Chuyển sang tiếng Trung",
  "列表已刷新": "Đã làm mới danh sách",
  "创建 ChatGPT 注册任务，数量": "Số lượng tác vụ đăng ký ChatGPT đã tạo",
  "创建 PayPal 任务": "Tạo tác vụ PayPal",
  "创建协议任务": "Tạo nhiệm vụ thỏa thuận",
  "创建单个或批量任务": "Tạo các tác vụ riêng lẻ hoặc hàng loạt",
  "创建或选择任务后显示当前阶段": "Hiển thị giai đoạn hiện tại sau khi tạo hoặc chọn một nhiệm vụ",
  "创建批量任务并处理短信验证码": "Tạo tác vụ hàng loạt và xử lý CAPTCHA qua SMS",
  "创建时间": "Thời gian sáng tạo",
  "初始化邮箱任务": "Khởi tạo tác vụ hộp thư",
  "删除": "Xoá",
  "删除全部": "Xoá tất cả",
  "删除分组": "Xoá nhóm",
  "删除号码": "Xóa số",
  "删除账号": "Xóa tài khoản",
  "删除选中": "Xóa mục đã chọn",
  "刷新": "Làm Mới",
  "刷新列表": "Làm mới danh sách",
  "刷新数据": "Làm mới dữ liệu",
  "刷新状态": "Làm mới trạng thái",
  "刷新账号状态": "Làm mới trạng thái tài khoản",
  "刷新页面": "Làm mới trang",
  "刷新额度": "Làm mới điểm tích lũy",
  "前进": "Tới",
  "功能配置": "Cấu hình chức năng",
  "加拿大": "người Ca-na-an",
  "加载安全卡片": "Nạp thẻ an toàn",
  "支付市场与双代理池": "Thị trường thanh toán và nhóm proxy kép",
  "支付市场": "Thị trường thanh toán",
  "加载项目": "Tải dự án",
  "匈牙利": "Hungary",
  "协议支付配置": "Cấu hình thanh toán theo thỏa thuận",
  "协议核心已隔离": "Giao thức lõi đã được cách ly",
  "协议模式": "Chế độ giao thức",
  "协议模式注册": "Đăng ký chế độ thỏa thuận",
  "协议流程会校验最终 VND 金额": "Quy trình thỏa thuận xác minh số tiền VND cuối cùng",
  "协议登录未完成，正在降级到后台无头登录": "Đăng nhập thỏa thuận chưa hoàn tất, hạ cấp xuống đăng nhập không đầu nền",
  "单号最高价格": "Giá tối đa cho một số",
  "南非": "Nam Phi",
  "占位能力，暂未开放选择": "Đối tượng chiếm giữ, lựa chọn chưa mở",
  "卡号": "Seri thẻ:",
  "卡塔尔": "Qatar",
  "卡片字段由 Stripe Elements 托管": "Các trường thẻ do Stripe Elements lưu trữ",
  "卡片组件加载失败": "Không thể tải thành phần thẻ",
  "卡片输入容器未就绪": "Hộp chứa đầu vào thẻ chưa sẵn sàng",
  "卢森堡": "Luxembourg",
  "印尼 Midtrans 跳转": "Nhảy trung chuyển Indonesia",
  "印度": "Ấn Độ",
  "印度二维码": "Mã QR Ấn Độ",
  "印度尼西亚": "Indonesia",
  "原 PIN": "Mã PIN ban đầu",
  "原 PIN 与新 PIN 必须是不同的 6 位数字": "Mã PIN ban đầu và mã PIN mới phải có 6 chữ số khác nhau",
  "原始协议流程": "Quy trình Hợp đồng Ban đầu",
  "原始卡片数据不落库": "Dữ liệu thẻ thô không rơi vào thư viện",
  "原生无头接管": "Ống không đầu bản địa",
  "双代理池": "Dual Proxy Pool",
  "反代": "kháng sinh",
  "反代导入": "Nhập khẩu chống thế hệ",
  "反代导入完成：选中 {selected} 个，提交 {uploaded} 个，确认成功 {confirmed} 个，失败 {failed} 个，跳过 {skipped} 个": "Đã hoàn tất nhập chống phát: {selected} đã chọn, gửi {uploaded}, xác nhận thành công {confirmed}, không thành công {failed}, bỏ qua {skipped}",
  "反代导入明细": "Chi tiết Nhập Chống Phát điện",
  "反代进度": "Tiến độ đảo ngược",
  "反代配置": "Cấu hình chống thay thế",
  "发件人": "Người gửi",
  "发起 Midtrans 支付": "Khởi tạo thanh toán trung chuyển",
  "发起支付任务": "Khởi tạo một nhiệm vụ thanh toán",
  "取件 API 公网地址": "Địa chỉ mạng công cộng API nhận hàng",
  "取消": "Hủy",
  "取消中": "Đang hủy",
  "取码 URL": "URL thu thập",
  "只看异常": "Chỉ trường hợp ngoại lệ",
  "可用": "Còn trống",
  "可用于接码": "Có thể được sử dụng để kết nối mã",
  "可用手机号 {count} 个": "Số điện thoại có sẵn {count}",
  "可视浏览器注册": "Đăng ký trình duyệt trực quan",
  "可视浏览器自动": "Tự động trình duyệt trực quan",
  "可选备用密钥": "Khóa sao lưu tùy chọn",
  "可选，优先使用 Solverify": "Tùy chọn, ưu tiên giải quyết",
  "号码与短信接口": "Số và giao diện SMS",
  "号码已删除": "Số đã bị xóa",
  "号码已导入": "Số đã nhập",
  "号码来源": "Nguồn số",
  "号码池": "Nhóm Số",
  "号码池为空": "Nhóm số trống",
  "号码池已清空": "Nhóm Số Lượng Trống",
  "号码池（可选）": "Number Pool (không bắt buộc)",
  "后台浏览器自动": "Tự động trình duyệt nền",
  "后续接码阶段未完成，账号保留为": "Giai đoạn kết nối mã tiếp theo chưa hoàn tất và tài khoản được dành riêng cho",
  "后退": "Quay lại",
  "否": "Không",
  "启动隔离浏览器": "Khởi chạy Trình duyệt Cách ly",
  "启用": "Khởi động",
  "启用 FireFox": "Bật FireFox",
  "启用 LubanSMS": "Bật LubanSMS",
  "启用 Remail": "Bật Remail",
  "启用 SMSBower": "Bật SMSBower",
  "启用 SMSPool": "Bật SMSPool",
  "启用优惠配置": "Bật cấu hình ưu đãi",
  "启用后，Checkout 请求将携带 0 元试用优惠条件": "Khi được bật, các yêu cầu Thanh toán sẽ có ưu đãi dùng thử trị giá 0 USD",
  "启用后，自动注册将按配置下单邮箱，并将订单邮箱写入自建邮箱池。": "Khi được bật, đăng ký tự động sẽ đặt một hộp thư đặt hàng như được định cấu hình và ghi hộp thư đặt hàng vào vùng hộp thư tự xây dựng.",
  "启用自建域名邮箱池": "Cho phép các nhóm hộp thư miền tự xây dựng",
  "哈萨克斯坦": "Kazakhstan",
  "哥伦比亚": "Colombia",
  "哥斯达黎加": "Khảm",
  "固定 CPF / CNPJ（选填）": "CPF/CNPJ cố định (không bắt buộc)",
  "国家": "quốc gia",
  "国家 / 地区": "Quốc gia",
  "国家代理池": "Quỹ Proxy Quốc gia",
  "国家代码": "Mã quốc gia:",
  "国家代码必须是两个大写英文字母，并且对应真实国家": "Mã quốc gia phải là hai chữ cái viết hoa bằng tiếng Anh và tương ứng với quốc gia thực",
  "土耳其": "Họa tiết",
  "在 iDEAL 支付页面选择": "Trên trang thanh toán iDEAL, chọn",
  "在新窗口打开支付链接": "Mở liên kết thanh toán trong cửa sổ mới",
  "埃及": "Ai Cập",
  "域名邮箱": "Email tên miền",
  "塞尔维亚": "Serbia",
  "塞浦路斯": "Cyprus",
  "墨西哥": "Mexico",
  "处理 OTP 与付款流程": "Xử lý OTP và Quy trình Thanh toán",
  "备注内容": "Nội dung bình luận",
  "复制": "sao chép",
  "复制 Checkout 链接": "Sao chép liên kết Thanh toán",
  "复制 MOMO 授权链接": "Sao chép liên kết ủy quyền Momo",
  "复制内容": "Sao chép nội dung",
  "复制图片": "Sao chép hình ảnh",
  "复制失败，请检查浏览器剪贴板权限": "Sao chép không thành công, vui lòng kiểm tra quyền truy cập khay nhớ tạm của trình duyệt",
  "复制成功": "Sao chép thành công",
  "复制支付链接": "Sao chép liên kết thanh toán",
  "复制链接": "Sao chép liên kết",
  "多米尼加共和国": "Cộng hòa Dominica",
  "多选时需同时具有所选国家的试用资格": "Nhiều lựa chọn yêu cầu đủ điều kiện dùng thử cho quốc gia đã chọn",
  "多选时需同时具有所选支付方式": "Nhiều lựa chọn cần phải có phương thức thanh toán đã chọn cùng một lúc",
  "失效": "mất đi hiệu lực",
  "失败": "Thất bại",
  "失败详情": "Chi tiết lỗi",
  "失败重试": "Thử lại không thành công",
  "失败重试次数": "Số lần thử lại không thành công",
  "套餐": "phần món ăn",
  "套餐筛选": "Lọc gói",
  "套餐类型": "Loại Gói",
  "奥地利": "Trừu tượng",
  "安全卡片": "Thẻ an toàn",
  "完成": "Hoàn thành",
  "完成 Agent Identity 反代导入": "Nhập danh tính hoàn chỉnh của nhân viên chăm sóc khách hàng chống phát sinh",
  "完成 Codex 接码绑定": "Gắn kết Codex hoàn chỉnh",
  "完成反代平台导入": "Nhập nền tảng chống phát điện hoàn chỉnh",
  "完成注册或登录后，账号会显示在这里": "Khi bạn đã đăng ký hoặc đăng nhập, tài khoản của bạn sẽ xuất hiện ở đây",
  "完成注册或登录认证": "Hoàn tất đăng ký hoặc xác thực đăng nhập",
  "完成账号 Session/RT 后导入已配置的 sub2api 反代平台": "Nhập nền tảng chống tạo sub2api được định cấu hình sau khi hoàn thành tài khoản Phiên/RT",
  "完成邮箱验证码验证": "Hoàn thành mã xác minh email",
  "官方支付长链": "Chuỗi dài thanh toán chính thức",
  "官方长链": "Chuỗi dài chính thức",
  "定时任务设置": "Cài đặt tác vụ đã lên lịch",
  "实时协议日志": "Nhật ký giao thức thời gian thực",
  "密码": "Mật khẩu",
  "导入": "Dẫn nhập",
  "导入 AT 后即可检测并创建任务": "Phát hiện và tạo nhiệm vụ sau khi nhập AT",
  "导入 sub2api 失败，账号保留为": "Không thể nhập sub2api, tài khoản được bảo lưu dưới dạng",
  "导入中...": "Đang nhập...",
  "导入列表": "Danh sách nhập",
  "导入到分组": "Nhập vào nhóm",
  "导入反代": "Nhập tạo nghịch đảo",
  "导入反代平台": "Nhập nền tảng chống phát sinh",
  "导入号码": "Nhập số",
  "导入完成": "Nhập hoàn tất",
  "导入手机号": "Nhập số điện thoại",
  "导入的 AT 已存在于列表中": "Đã nhập AT đã tồn tại trong danh sách",
  "导入账号": "Nhập tài khoản",
  "导入账号后即可分配环境并创建任务": "Sau khi tài khoản của bạn được nhập, bạn có thể chỉ định môi trường và tạo nhiệm vụ",
  "导入账号已存在于列表中": "Nhập tài khoản đã tồn tại trong danh sách",
  "导入账户 AT": "Nhập tài khoản tại",
  "导入账户 Access Token": "Nhập mã thông báo truy cập tài khoản",
  "导入邮箱": "Nhập email",
  "导出": "xuất file",
  "导出 CSV": "Xuất CSV",
  "导出AT": "Xuất tại",
  "导出LS": "Xuất LS",
  "导出SK": "Xuất SK",
  "导出SUB": "Xuất phụ",
  "导出内容": "Xuất nội dung",
  "导出完成": "Hoàn tất xuất",
  "导出操作结束": "Kết thúc hoạt động xuất khẩu",
  "封": "phong",
  "将选中账户换绑为自建域名邮箱": "Đổi tài khoản đã chọn lấy email tên miền tự tạo",
  "尚未加载": "Chưa tải",
  "尚未配置代理池": "Không có nhóm proxy nào được định cấu hình",
  "尼日利亚": "Nối tiếp",
  "展开": "mở ra",
  "展开 Remail 配置": "Mở rộng cấu hình chuyển tiền",
  "展开自建域名邮箱配置": "Mở rộng cấu hình email tên miền tự xây dựng",
  "工作台": "Bàn làm việc",
  "工作空间": "Không gian làm việc",
  "已保存有效 Session": "Một phiên hợp lệ đã được lưu",
  "已修改并确认": "Đã sửa đổi và xác nhận",
  "已修改，待确认": "Đã sửa đổi, đang chờ xác nhận",
  "已停止": "Bị dừng",
  "已停止恢复本地 MOMO 任务，可重新提交": "Đã dừng khôi phục các tác vụ Momo cục bộ, có thể gửi lại",
  "已反代": "Thế hệ đảo ngược",
  "已取消": "Ô ký tự",
  "已失败": "Không thành công",
  "已存在": "Đã tồn tại",
  "已完成": "Đã hoàn thành",
  "已完成注册": "Đăng ký đã hoàn tất",
  "已导入 AT": "Khi nhập",
  "已封禁": "Bóng ma",
  "已成功": "Thành công",
  "已捕获 OAuth callback，正在交换 Refresh Token": "Đã ghi lại cuộc gọi lại OAuth, trao đổi Mã làm mới",
  "已换绑": "Gắn kết đã thay đổi",
  "已接码": "Mã hóa",
  "已有 PIN，未验证": "Mã PIN đã tồn tại, chưa được xác minh",
  "已有空间 ID": "ID không gian hiện có",
  "已注册": "Đã đăng ký",
  "已清理注册历史": "Đã xóa lịch sử đăng ký",
  "已生效": "Đang hoạt động",
  "已用次数": "Số lượng đã sử dụng",
  "已自动点击 Codex 授权继续按钮": "Nút tiếp tục ủy quyền Codex được nhấp tự động",
  "已获取 {count} 个目标分组": "Đã nhận được {count} nhóm mục tiêu",
  "已获取新 Access Token": "Đã nhận được mã thông báo truy cập mới",
  "已设置": "Bộ",
  "已请求停止 MOMO 任务": "Đã yêu cầu dừng tác vụ Momo",
  "已请求停止提链任务": "Đã yêu cầu dừng tác vụ chuỗi",
  "已请求停止整批注册任务，正在关闭任务进程、浏览器与邮箱读取资源": "Đã yêu cầu dừng các tác vụ ghi danh hàng loạt, đóng quy trình tác vụ, tài nguyên đọc trình duyệt và hộp thư",
  "已请求停止续期任务，正在关闭当前续期流程；等待中的账户将不再执行": "Đã yêu cầu dừng nhiệm vụ gia hạn, đóng quy trình gia hạn hiện tại; các tài khoản đang chờ xử lý sẽ không còn thực thi",
  "已请求终止当前日志对应的任务": "Yêu cầu chấm dứt nhiệm vụ tương ứng với nhật ký hiện tại",
  "已跳过已封禁账户": "Đã bỏ qua tài khoản bị cấm",
  "已过期": "Đã hết hạn",
  "已选": "đã chọn",
  "已选 {count} 项": "Đã chọn {count} mục",
  "已选中当前筛选结果中的 {count} 条记录": "Đã chọn {count} bản ghi trong kết quả lọc hiện tại",
  "已选择": "Đã chọn",
  "已选择 ": "Đã chọn",
  "已通过页面原生表单提交邮箱验证码": "Mã xác minh email được gửi qua biểu mẫu gốc của trang",
  "已配置，留空保持不变": "Đã định cấu hình, để trống để không thay đổi",
  "已领取": "Đã nhận",
  "巴拉圭": "Tiệc",
  "巴林": "Thu nhỏ",
  "巴西": "Brazil",
  "巴西即时支付": "Thanh toán nhanh Brazil",
  "币种": "Tiền tệ",
  "希腊": "Lục",
  "席位数量": "Số chỗ",
  "并发": "đồng phát",
  "并发数": "Số lần đồng thời",
  "并发量": "Đồng thời",
  "应用 Plus 优惠": "Áp dụng khuyến mãi Plus",
  "应用到选中的邮箱": "Áp dụng cho các hộp thư đã chọn",
  "延迟": "kéo dài",
  "建立纯协议注册会话": "Thiết lập phiên ghi danh chỉ theo thỏa thuận",
  "开启": "mở ra",
  "开启优惠时请填写 Promotion 代理池": "Vui lòng điền vào Nhóm Đại lý Khuyến mãi khi mở ưu đãi",
  "开始 MOMO 任务": "Bắt đầu tác vụ Momo",
  "开始批量任务": "Bắt đầu tác vụ hàng loạt",
  "开始探测": "Bắt đầu thăm dò",
  "开始提链": "Bắt đầu nâng xích",
  "开始检测": "Bắt đầu kiểm tra",
  "开始自动注册": "Bắt đầu ghi danh tự động",
  "开始补充登录密钥": "Bắt đầu khóa đăng nhập bổ sung",
  "当前 Access Token 已确认失效，等待恢复": "Mã thông báo truy cập hiện tại đã được xác nhận là không hợp lệ và đang chờ khôi phục",
  "当前 Access Token 有效，无需重新登录": "Mã thông báo truy cập hiện tại hợp lệ, không cần đăng nhập lại",
  "当前 Access Token 状态未能确认": "Không thể xác nhận trạng thái Mã thông báo truy cập hiện tại",
  "当前AT无效，已启动AT续期任务": "Đã bắt đầu tác vụ gia hạn AT, AT hiện tại không hợp lệ",
  "当前AT有效，无需续期": "AT hiện tại hợp lệ và không cần gia hạn",
  "当前优先使用自建 Outlook/Hotmail 邮箱池进行邮箱验证。": "Hiện tại, ưu tiên xác minh hộp thư bằng cách sử dụng nhóm hộp thư Outlook/Hotmail tự xây dựng.",
  "当前完成": "Hoàn thành hiện tại",
  "当前平台没有找到任何账号记录。请先到邮箱配置中导入邮箱，然后选择邮箱进行自动注册。": "Không tìm thấy bản ghi tài khoản nào trên nền tảng hiện tại. Trước tiên, vui lòng nhập hộp thư vào cấu hình hộp thư, sau đó chọn hộp thư để đăng ký tự động.",
  "当前未开启 Plus 优惠，无需进行试用资格检测": "Ưu đãi Plus hiện không hoạt động, không yêu cầu xét nghiệm đủ điều kiện dùng thử",
  "当前步骤": "Các bước hiện tại",
  "当前注册任务正在执行，请等待任务结束或先停止任务": "Tác vụ đăng ký hiện đang thực hiện, vui lòng đợi tác vụ kết thúc hoặc dừng tác vụ trước",
  "当前消息": "Tin nhắn hiện tại",
  "当前筛选没有可选账户": "Không có tài khoản khả dụng cho bộ lọc hiện tại",
  "当前账户已全部选择，请使用清除选择": "Tài khoản hiện tại đã được chọn, vui lòng sử dụng Xóa lựa chọn",
  "当前账户未接码，请先完成接码后再获取RT": "Tài khoản hiện tại không nhận được mã, vui lòng hoàn thành mã trước khi nhận RT",
  "当前邮箱": "Email hiện tại",
  "当前邮箱日志": "Nhật ký email hiện tại",
  "当前阶段": "Giai đoạn hiện tại",
  "当前预览仅支持网页链接和 GET 表单跳转": "Bản xem trước hiện tại chỉ hỗ trợ các liên kết web và nhận các bước nhảy biểu mẫu",
  "当自建手机号池不可用或无可用号码时，注册机会使用 SMSBower API 自动获取一次性手机号。": "Khi nhóm điện thoại tự xây dựng không khả dụng hoặc không có số khả dụng, cơ hội đăng ký sẽ sử dụng API SMSBower để tự động nhận số điện thoại một lần.",
  "待二验": "Được xét nghiệm hai lần",
  "待处理": "Đang chờ xử lý",
  "待执行": "Đang chờ xử lý",
  "待检测": "Sẽ được kiểm tra",
  "待注册": "Sẽ được đăng ký",
  "待确认": "Sẽ được xác nhận",
  "微软邮箱": "Microsoft Mail",
  "微软邮箱支持 OAuth 四段凭证；Apple iCloud 邮箱按所选渠道使用 API 查询邮件与验证码。": "Hộp thư của Microsoft hỗ trợ thông tin đăng nhập bốn phân đoạn OAuth; hộp thư Apple iCloud sử dụng API để truy vấn thư và mã xác minh theo kênh đã chọn.",
  "德国": "Đức",
  "快速操作": "Hành động nhanh",
  "总览": "quan sát",
  "总计": "TỔNG QUAN",
  "意大利": "Ý",
  "成功": "thành công",
  "成功 ": "thành công",
  "成功·待收尾": "Thành công · Sẽ được ký kết",
  "成功账户": "Tài khoản thành công",
  "成功链接": "Liên kết thành công",
  "我已核对订单并确认开始支付": "Tôi đã xem xét đơn hàng và xác nhận bắt đầu thanh toán",
  "所属分组": "Các nhóm mà bạn tham gia",
  "所选账号已有 RT，无需接码": "Tài khoản đã chọn đã có RT, không cần kết nối mã",
  "手动导入": "Nhập thủ công",
  "手动新增": "Thêm thủ công",
  "手机": "điện thoại",
  "手机号": "SĐT",
  "手机号导入格式错误": "Lỗi định dạng nhập số điện thoại",
  "手机号（含国家码）": "Số điện thoại (bao gồm mã quốc gia)",
  "打开": "Open",
  "打开 MOMO 授权链接": "Mở liên kết Ủy quyền Momo",
  "扣款结果": "Kết quả tính phí",
  "执行并发量": "Thực hiện khối lượng đồng thời",
  "执行方式": "Phương thức thực hiện",
  "执行时间": "Thời gian thực hiện:",
  "执行频率（小时）": "Tần suất thực hiện (Giờ)",
  "批次执行失败": "Thực hiện hàng loạt không thành công",
  "批量任务已创建": "Đã tạo tác vụ hàng loạt",
  "批量修改": "Chỉnh sửa hàng loạt",
  "批量删除": "Xóa hàng loạt",
  "批量功能并发": "Đồng thời hàm số lượng lớn",
  "批量检测": "Kiểm tra hàng loạt",
  "批量编辑": "Chỉnh sửa hàng loạt",
  "批量编辑邮箱": "Chỉnh sửa hàng loạt email",
  "折叠 Remail 配置": "Thu gọn cấu hình sửa lại",
  "折叠自建域名邮箱配置": "Thu gọn cấu hình email miền tự xây dựng",
  "拉脱维亚": "Latvia",
  "拖动调整列宽，双击恢复默认宽度": "Kéo để điều chỉnh chiều rộng cột, nhấp đúp để khôi phục chiều rộng mặc định",
  "拖动调整日志窗口大小": "Kéo để thay đổi kích thước cửa sổ nhật ký",
  "拖拽邮箱文件到这里，或点击选择文件": "Thả tệp email của bạn ở đây hoặc nhấp để chọn tệp",
  "指纹分配失败": "Phân bổ dấu vân tay không thành công",
  "按年": "Hàng năm",
  "按支付方式维护号码供应商与 GoPay 人机验证": "Duy trì số lượng nhà cung cấp và xác minh máy móc của GoPay bằng phương thức thanh toán",
  "按支付路径默认": "Theo đường dẫn thanh toán mặc định",
  "按月": "theo tháng",
  "挪威": "Chuẩn",
  "换绑": "Liên kết hoán đổi",
  "换绑中": "Thay đổi liên kết",
  "换绑进度": "Tiến độ Liên kết Thay đổi",
  "换绑邮箱": "Thay đổi email liên kết",
  "换绑邮箱 API": "API hộp thư trao đổi",
  "换绑邮箱名": "Thay đổi tên email",
  "捷克": "Cộng hòa Séc",
  "排队中": "Đã xếp hàng",
  "探测中...": "Đang thăm dò...",
  "接口地址": "Địa chỉ giao diện",
  "接码配置": "Cấu hình kết nối",
  "接码链接": "Liên kết mã vá lỗi",
  "控制本次任务执行到哪个阶段，默认仅完成 ChatGPT 注册/登录与 Session 存储。": "Kiểm soát giai đoạn thực hiện nhiệm vụ này. Theo mặc định, chỉ đăng ký/đăng nhập ChatGPT và lưu trữ Phiên được hoàn thành.",
  "提交": "nộp",
  "提交注册邮箱": "Gửi email đăng ký",
  "提链 + 支付": "Đơn vị vận chuyển + Thanh toán",
  "提链 + 绑卡": "Mang xích + gắn thẻ",
  "提链 + 绑卡 + 提链 + 支付": "Chuỗi mang + Gắn thẻ + Chuỗi mang + Thanh toán",
  "提链 · 优惠地区节点": "Chuỗi mang · Nút vùng ưu tiên",
  "提链中...": "Xích nâng...",
  "提链代理已就绪": "Chất nâng đã sẵn sàng",
  "提链任务完成": "Hoàn thành nhiệm vụ nâng xích",
  "提链任务已完成": "Nhiệm vụ nâng xích đã hoàn thành",
  "提链任务已提交，任务状态和日志将在后台持续同步": "Tác vụ chuỗi đã được gửi và trạng thái tác vụ và nhật ký sẽ tiếp tục được đồng bộ hóa trong nền",
  "提链任务已结束": "Nhiệm vụ chọn chuỗi đã kết thúc",
  "提链任务状态暂时读取失败，正在继续重试": "Tạm thời không thể đọc trạng thái tác vụ chuỗi, tiếp tục thử lại",
  "提链任务结束，请查看结果": "Nhiệm vụ chuỗi đã kết thúc, vui lòng kiểm tra kết quả",
  "提链处理中": "Xích nâng gia công",
  "提链失败：": "Nâng xích không thành công:",
  "提链并发": "Chainlifting Concurrency",
  "提链日志": "Nhật ký xích mang",
  "提链管理": "Quản lý chuỗi vận chuyển",
  "搜索 ID、代码或名称...": "Tìm kiếm giấy tờ tùy thân, mã hoặc tên...",
  "搜索代理地址...": "Tìm kiếm địa chỉ proxy...",
  "搜索手机号": "Tìm kiếm số điện thoại",
  "搜索手机号...": "Tìm kiếm số điện thoại...",
  "搜索手机号或 Customer ID": "Tìm kiếm số điện thoại hoặc ID khách hàng",
  "搜索账号邮箱...": "Tìm kiếm email tài khoản...",
  "搜索邮箱/换绑邮箱": "Tìm kiếm hộp thư/Tìm lại hộp thư",
  "搜索邮箱分组...": "Tìm kiếm nhóm hộp thư...",
  "搜索邮箱或换绑邮箱...": "Tìm kiếm hoặc thay đổi email...",
  "操作": "Thao tác",
  "操作失败": "Thao tác thất bại",
  "操作完成": "Hoạt động hoàn tất",
  "支付": "chi trả",
  "支付 OTP 已提交": "Đã gửi OTP thanh toán",
  "支付中心": "Trung tâm thanh toán",
  "支付二维码": "Mã QR thanh toán",
  "支付任务": "Nhiệm vụ thanh toán",
  "支付任务已创建": "Đã tạo tác vụ thanh toán",
  "支付历史已清理": "Đã xóa lịch sử thanh toán",
  "支付探测": "Đầu dò thanh toán",
  "支付探测完成：检测成功 {detected} 个，部分完成 {partial} 个，跳过 {skipped} 个，失败 {failed} 个": "Đã hoàn tất phát hiện thanh toán: {detected}, đã hoàn thành một phần {partial}, đã bỏ qua {skipped}, không thành công {failed}",
  "支付探测进度": "Tiến độ Thăm dò Lương",
  "支付探测（国家）": "Phát hiện thanh toán (Quốc gia)",
  "支付探测（账户）": "Phát hiện thanh toán (tài khoản)",
  "支付方式": "Phương thức thanh toán",
  "支付方式筛选（同时满足）": "Lọc phương thức thanh toán (trong khi vẫn đáp ứng)",
  "支付检测": "Phát hiện thanh toán",
  "支付流程": "Quy trình thanh toán",
  "支付管理": "Quản lý thanh toán",
  "支付路径": "Đường dẫn thanh toán",
  "支付链接": "Liên kết thanh toán",
  "支付链接已复制": "Đã sao chép liên kết thanh toán",
  "支持后台浏览器自动与可视浏览器自动；后台模式不显示窗口，更适合批量执行。": "Hỗ trợ trình duyệt nền tự động và trình duyệt trực quan tự động; chế độ nền không hiển thị cửa sổ, phù hợp hơn để thực thi hàng loạt.",
  "支持纯协议、后台浏览器与可视浏览器自动；协议模式不加载网页资源，流量占用更低。": "Hỗ trợ tự động hóa giao thức, trình duyệt nền và trình duyệt trực quan; chế độ giao thức không tải tài nguyên web và lưu lượng truy cập chiếm ít hơn.",
  "收件人": "Người nhận",
  "收件箱": "Hòm thư",
  "收到并提交手机验证码": "Nhận và gửi mã xác minh di động",
  "收起": "thu vào",
  "放弃恢复": "Hủy khôi phục",
  "数量": "KL",
  "文件导入": "Nhập tệp",
  "斯洛伐克": "Slovakia",
  "斯洛文尼亚": "Slovenia",
  "新 PIN": "Mã PIN mới",
  "新 Session 已读取并通过验活": "Phiên mới đã đọc và vượt qua",
  "新加坡": "Singapore",
  "新增代理": "Thêm proxy",
  "新建分组": "Nhóm mới",
  "新建批量任务": "Tác vụ hàng loạt mới",
  "新西兰": "New Zealand",
  "新邮箱": "Email mới",
  "无 LS": "Không LS",
  "无0元试用": "Không dùng thử $ 0",
  "无2FA": "Không có 2FA",
  "无头浏览器注册": "Đăng ký trình duyệt không đầu",
  "无密码": "Không có mật khẩu",
  "无效": "không có hiệu quả",
  "无法获取该账户RT": "Không thể tải RT cho tài khoản này",
  "无窗口 Headless 执行，仍使用隔离无痕浏览器上下文自动注册": "Không thực thi không có cửa sổ, vẫn ghi danh tự động với bối cảnh trình duyệt ẩn danh được cách ly",
  "无试用": "Không dùng thử",
  "无试用：": "Không dùng thử:",
  "日志": "nhật ký",
  "日本": "Japan",
  "时间": "Thời gian",
  "是": "Có",
  "显示 ": "biểu hiện",
  "显示 {from} 至 {to} 共 {total} 条结果": "Hiển thị {from} đến {to} trong số {total} kết quả",
  "显示提链日志": "Hiển thị chuỗi nhật ký lưu ký",
  "显示明文": "Hiển thị văn bản rõ ràng",
  "显示账户管理日志": "Hiển thị nhật ký quản lý tài khoản",
  "智利": "Trẻ",
  "暂无 GoPay 账号": "Chưa có tài khoản GoPay",
  "暂无 MOMO 任务": "Chưa có tác vụ Momo nào",
  "暂无 MOMO 支付账户": "Không có tài khoản thanh toán Momo",
  "暂无 PayPal 协议任务": "Không có nhiệm vụ thỏa thuận PayPal",
  "暂无代理": "Chưa có nhân viên chăm sóc khách hàng",
  "暂无任务": "Chưa có tác vụ nào",
  "暂无分组，请点击右侧“获取”": "Chưa có nhóm nào, vui lòng nhấp vào \"Nhận\" ở bên phải",
  "暂无可用的支付探测国家代理": "Không có đại lý quốc gia về thăm dò thanh toán",
  "暂无可用的账户检测国家代理": "Không có tài khoản để phát hiện các đại lý quốc gia",
  "暂无已探测支付方式": "Không phát hiện phương thức thanh toán nào",
  "暂无已检测国家": "Chưa có quốc gia nào được phát hiện",
  "暂无提链日志": "Không có nhật ký nâng xích",
  "暂无支付任务": "Chưa có tác vụ thanh toán nào",
  "暂无数据": "Chưa có dữ liệu",
  "暂无日志": "Chưa có nhật ký",
  "暂无正在处理的邮箱账户": "Không có tài khoản email nào đang được tiến hành",
  "暂无注册任务": "Chưa có tác vụ ghi danh nào",
  "暂无直卡协议账号": "Không có tài khoản thỏa thuận thẻ trực tiếp",
  "暂无结果日志": "Chưa có nhật ký kết quả",
  "暂无该账户提链日志": "Không có nhật ký chuỗi cho tài khoản này",
  "暂无详细日志": "Không có nhật ký chi tiết",
  "暂无账户，请先导入或选择 AT。": "Không CÓ tài khoản, vui lòng nhập hoặc chọn lúc trước.",
  "暂无过程日志": "Chưa có nhật ký quy trình nào",
  "暂无邮件": "Chưa có tin nhắn nào",
  "暂无邮箱": "Chưa có hộp thư nào",
  "更新于 ": "Cập nhật lúc",
  "更新时间": "thời gian cập nhật",
  "最多 100 条，空行与重复项自动忽略": "Tối đa 100, các dòng trống và bản sao sẽ tự động bị bỏ qua",
  "最大价格": "Giá tối đa",
  "最大重试次数": "Số lần thử lại tối đa",
  "最近任务": "Nhiệm vụ gần đây",
  "最近使用时间": "Sử dụng lần cuối",
  "最近提链任务": "Các nhiệm vụ nâng cao chuỗi gần đây",
  "最近活动": "Hoạt động gần đây",
  "最近测活时间": "Thời gian hoạt động cuối cùng",
  "最高价格（可选）": "Giá tối đa (không bắt buộc)",
  "有 LS": "Có LS",
  "有0元试用": "Có bản dùng thử $ 0",
  "有2FA": "Có 2FA",
  "有密码": "Có mật khẩu",
  "有效": "Hợp lệ",
  "有效 ": "Hợp lệ ",
  "有效期": "thời hạn hiệu lực",
  "有试用": "Có dùng thử",
  "服务代码": "Mã Dịch Vụ",
  "服务模式": "Chế độ dịch vụ",
  "服务端未返回 MOMO 任务标识": "Máy chủ không trả lại ID nhiệm vụ Momo",
  "未发现 Refresh Token，切换登录流程": "Không tìm thấy mã thông báo làm mới, hãy chuyển đổi quy trình đăng nhập",
  "未命名账号": "Tài khoản chưa đặt tên",
  "未完成注册": "Đăng ký chưa hoàn tất",
  "未开始": "Chưa bắt đầu",
  "未换绑": "Gắn kết không thay đổi",
  "未检测": "Không phát hiện",
  "未注册": "Chưa đăng ký",
  "未生效": "Không hoạt động",
  "未知账户": "Tài khoản không xác định",
  "未知邮箱": "Email không xác định",
  "未设置": "Chưa thiết lập",
  "未运行": "Chưa chạy",
  "未选择账户": "Không có tài khoản nào được chọn",
  "本地号": "Số điện thoại địa phương",
  "本机已保存": "Đã lưu bản địa",
  "本机未保存": "Máy này chưa được lưu",
  "本页全选": "Chọn tất cả trên trang này",
  "来源": "khởi nguồn",
  "查余额": "Kiểm tra số dư",
  "查看 {field}": "Xem {field}",
  "查看二维码": "Xem mã QR",
  "查看当前账户提链日志": "Xem nhật ký chuỗi tài khoản hiện tại",
  "查询 Key": "Khóa truy vấn",
  "查询余额 / 测试连接": "Truy vấn kết nối cân bằng/kiểm tra",
  "查询数量": "Số lượng truy vấn",
  "查询最近邮件": "Truy vấn tin nhắn gần đây",
  "校验失败": "Xác minh không thành công",
  "校验通过": "Đã vượt qua xác minh",
  "格式无效": "Định dạng không hợp lệ",
  "格式：+手机号----接码链接。成功后冷却 5 小时，最多 3 次。": "Định dạng: + Số điện thoại ---- Liên kết mã tiếp nhận. Làm mát trong 5 giờ sau khi thành công, tối đa 3 lần.",
  "格鲁吉亚": "Nối tiếp",
  "检查账号": "Kiểm tra lại tài khoản của bạn",
  "检测": "kiểm tra",
  "检测 PIN": "Kiểm tra mã PIN",
  "检测中": "Phát hiện",
  "检测中...": "Đang phát hiện...",
  "检测代理": "Chất phát hiện",
  "检测余额": "Kiểm tra số dư",
  "检测信息": "Thông tin phát hiện",
  "检测到上次注册任务仍在进行，已恢复日志轮询": "Nhiệm vụ ghi danh cuối cùng vẫn đang được phát hiện, tiếp tục bỏ phiếu nhật ký",
  "检测失败": "Kiểm tra không thành công",
  "检测失败：{error}": "Kiểm tra không thành công: {error}",
  "检测资格 / Checkout": "Điều kiện xét nghiệm/Trả phòng",
  "检测连接": "Phát hiện kết nối",
  "检测通过": "Đã vượt qua bài kiểm tra",
  "检测通过，发现 {count} 个分组": "Đã vượt qua bài kiểm tra, đã tìm thấy các nhóm {count}",
  "模型白名单": "Danh sách trắng mẫu",
  "模式": "Kiểu mẫu",
  "次数筛选": "Số lượng bộ lọc",
  "正在保存已验活 Session": "Lưu phiên trực tiếp",
  "正在停止后续账号任务": "Dừng các tác vụ tài khoản theo dõi",
  "正在停止续期任务": "Dừng nhiệm vụ gia hạn",
  "正在准备失效账户恢复": "Chuẩn bị khôi phục tài khoản bị vô hiệu hóa",
  "正在分配环境指纹": "Gán dấu vân tay môi trường",
  "正在创建 Agent Identity 并导入反代平台": "Tạo danh tính đại lý và nhập nền tảng chống phát sinh",
  "正在加载 Checkout、账单地址与 Stripe 安全组件": "Đang tải Thanh toán, Địa chỉ Thanh toán và Thành phần Bảo mật Stripe",
  "正在加载支付模块...": "Đang tải mô-đun thanh toán...",
  "正在加载邮件页面": "Đang tải trang thư",
  "正在启动协议登录与原生挑战接管": "Bắt đầu đăng nhập giao thức với tiếp quản thách thức bản địa",
  "正在启动后台无头登录": "Bắt đầu đăng nhập không đầu trong nền",
  "正在完成账户登录验证": "Hoàn tất xác minh đăng nhập tài khoản",
  "正在对新 Access Token 二次验活": "Thử nghiệm Mã thông báo truy cập mới lần thứ hai",
  "正在导入反代平台": "Nhập các nền tảng chống tạo sinh",
  "正在并发检测当前 Access Token": "Phát hiện đồng thời Mã thông báo truy cập hiện tại",
  "正在恢复任务状态": "Đang khôi phục trạng thái tác vụ",
  "正在更新数据...": "Đang cập nhật dữ liệu...",
  "正在检测并更新 Access Token": "Phát hiện và cập nhật Mã thông báo truy cập",
  "正在添加 ChatGPT 密码": "Thêm mật khẩu ChatGPT",
  "正在生成安全支付方式": "Tạo phương thức thanh toán an toàn",
  "正在绑定 ChatGPT 2FA": "Trò chuyện Gắn kếtGPT 2FA",
  "正在获取 {field}，请耐心等待...": "Đang nhận {field}, vui lòng kiên nhẫn...",
  "正在获取RT": "Nhận RT",
  "正在读取并更新 Session": "Đọc và cập nhật Buổi học",
  "此操作可能直接产生真实扣款，请核对账号、订单与金额。": "Hành động này có thể trực tiếp dẫn đến một khoản phí thực tế. Vui lòng kiểm tra số tài khoản, đơn hàng và số tiền.",
  "步骤": "Bước",
  "每个代理池最多 500 条。每轮重试会重新选择代理组合；Checkout 创建与支付处理使用 Checkout 代理池，试用检查与优惠更新使用 Promotion 代理池。": "Tối đa 500 cho mỗi nhóm proxy. Mỗi vòng thử lại sẽ chọn lại tổ hợp đại lý; tạo và xử lý thanh toán Thanh toán sẽ sử dụng nhóm đại lý Thanh toán, và kiểm tra dùng thử và cập nhật khuyến mãi sẽ sử dụng nhóm đại lý Khuyến mãi.",
  "每个任务独立使用一个 BA 链接、手机号和代理出口，可同时运行多个任务": "Một liên kết BA, số điện thoại và lối ra proxy được sử dụng độc lập cho mỗi tác vụ và có thể chạy nhiều tác vụ cùng một lúc",
  "每个账号自动获取独立账单地址": "Tự động nhận một địa chỉ thanh toán duy nhất cho mỗi tài khoản",
  "每次提交都会创建独立任务；请为不同任务使用不同 BA 链接和手机号。": "Các nhiệm vụ riêng biệt được tạo cho mỗi lần gửi; sử dụng các liên kết BA và số điện thoại khác nhau cho các nhiệm vụ khác nhau.",
  "每行一个 AT，支持任意数量；内容仅保存在当前浏览器本地": "Một AT trên mỗi dòng, hỗ trợ bất kỳ số nào; nội dung chỉ được lưu cục bộ trong trình duyệt hiện tại",
  "每行一个 Access Token": "Một mã thông báo truy cập mỗi dòng",
  "每行一个 Access Token，也支持包含 access_token 的 JSON / JSONL": "Một Access Token trên mỗi dòng, JSON/JSONL với access_token cũng được hỗ trợ",
  "每行一个 HTTP、HTTPS 或 SOCKS 代理": "Một proxy http, https hoặc SOCKS trên mỗi dòng",
  "每行一个 HTTP、HTTPS 或 SOCKS5 代理": "Một proxy http, https hoặc socks5 trên mỗi dòng",
  "每行一个代理，例如 http://user:pass@host:port 或 socks5://host:port": "Một proxy trên mỗi dòng, ví dụ: http://user:pass@host:port hoặc socks5://host: port",
  "每行一个代理，支持 http://、https://、socks5://": "Một đại lý mỗi dòng cho http://、https://、socks5://",
  "每行一个长效接码：第一个字符必须是 +，手机号与接码链接之间必须使用四个中横线 ---- 连接。": "Một đầu nối tác dụng dài trên mỗi dòng: ký tự đầu tiên phải là + và bốn đường ngang giữa phải được sử dụng giữa số điện thoại di động và liên kết đầu nối ---- kết nối.",
  "每行一条 HTTP、HTTPS 或 SOCKS5 代理": "Một proxy http, https hoặc socks5 trên mỗi dòng",
  "每行一条 host:port:user:password；需与账单国家匹配": "Máy chủ lưu trữ một dòng: cổng: người dùng: mật khẩu; cần khớp với quốc gia thanh toán",
  "每页": "Mỗi trang",
  "每页:": "Trên mỗi trang:",
  "比利时": "Bỉ",
  "沙特阿拉伯": "Ả Rập Xê Út",
  "没有匹配的选项": "Không có tùy chọn phù hợp",
  "没有匹配的邮箱分组": "Không có nhóm hộp thư phù hợp",
  "没有识别到包含账号 ID 的 Access Token": "Mã thông báo truy cập có ID tài khoản không được nhận dạng",
  "没有识别到可导入的 AT": "Không xác định được AT nhập khẩu",
  "法国": "nước Pháp",
  "波兰": "Hà Lang",
  "波兰银行动态码支付": "Thanh toán bằng Mã động của Ngân hàng Ba Lan",
  "注册": "ghi danh",
  "注册/登录": "Đăng ký/Đăng nhập",
  "注册/登录后使用 Access Token 创建 Agent Identity，跳过手机号绑定并直接导入 sub2api": "Sau khi đăng ký/đăng nhập, sử dụng Access Token để tạo Danh tính Đại lý, bỏ qua việc liên kết số điện thoại và nhập trực tiếp sub2api",
  "注册/登录后继续使用接码配置完成手机验证并获取 Refresh Token": "Sau khi đăng ký/đăng nhập, tiếp tục sử dụng cấu hình mã kết nối để hoàn tất xác minh số điện thoại và nhận Mã làm mới",
  "注册/登录请求走代理池": "Đăng ký/Đăng nhập Yêu cầu gỡ bỏ Proxy Pool",
  "注册与登录": "Đăng ký & Đăng nhập",
  "注册中": "Đăng ký",
  "注册任务已提交，正在开始执行": "Nhiệm vụ đăng ký đã được gửi và đang bắt đầu thực hiện",
  "注册任务进度": "Tiến độ đăng ký nhiệm vụ",
  "注册或登录": "Đăng ký hoặc đăng nhập",
  "注册或登录成功后，只读取并保存 ChatGPT Session 信息": "Chỉ đọc và lưu thông tin Phiên ChatGPT sau khi đăng ký hoặc đăng nhập thành công",
  "注册或登录账号": "Đăng ký hoặc đăng nhập",
  "注册数量": "Số lượng đăng ký",
  "注册新号": "Đăng ký số mới",
  "注册时间": "Thời gian đăng ký",
  "注册流程异常": "Quy trình đăng ký bất thường",
  "注册流量代理": "Đăng ký ủy quyền lưu lượng truy cập",
  "注册状态异常": "Ngoại lệ về trạng thái ghi danh",
  "注册请求保持协议模式，仅用窄范围 Camoufox 生成浏览器证明": "Đăng ký chế độ thỏa thuận giữ yêu cầu, chỉ tạo bằng chứng trình duyệt với Camoufox phạm vi hẹp",
  "注册账号": "Đăng ký tài khoản",
  "注册身份": "Danh tính đã đăng ký",
  "注册阶段": "Giai đoạn ghi danh",
  "泰国": "nước Thái",
  "流程日志": "Nhật ký quy trình",
  "流量消耗": "Tiêu thụ lưu lượng truy cập",
  "测活": "Đo lường hoạt động",
  "测活中...": "Đang kiểm tra...",
  "测活完成：测试 {total} 个，存活 {alive} 个，封禁 {banned} 个，跳过 {skipped} 个，失败 {failed} 个": "Hoàn thành kiểm tra hoạt động: Test {total}, Survive {alive}, Ban {banned}, Skip {skipped}, Fail {failed}",
  "测活进度": "Tiến độ đo lường hoạt động",
  "测试连接": "Kiểm tra kết nối",
  "浏览器挑战策略": "Chiến lược Thử thách Trình duyệt",
  "消息": "tin tức",
  "添加LS": "Thêm LS",
  "添加LS信息": "Thêm thông tin LS",
  "添加LS进度": "Thêm tiến độ LS",
  "添加SK信息": "Thêm thông tin SK",
  "添加中...": "Đang thêm...",
  "添加密码2FA": "Thêm mật khẩu 2FA",
  "添加自定义信息": "Thêm thông tin tùy chỉnh",
  "清理已结束": "Đã hoàn tất dọn dẹp",
  "清空": "dọn sạch",
  "清空列表": "Danh sách trống",
  "清除": "thanh trừ",
  "清除当前日志": "Xóa nhật ký hiện tại",
  "清除支付方式筛选": "Xóa bộ lọc phương thức thanh toán",
  "清除现有凭证": "Xóa phiếu quà tặng hiện có",
  "清除筛选": "Xóa bộ lọc",
  "清除选择": "Xóa lựa chọn",
  "渠道类型": "Loại kênh",
  "澳大利亚": "Trung lập",
  "爱尔兰": "Ireland",
  "爱沙尼亚": "Estonia",
  "状态": "Trạng thái",
  "状态变更时间": "Thời gian thay đổi trạng thái",
  "状态筛选": "Bộ lọc trạng thái",
  "状态：": "Trạng thái:",
  "环境": "Môi trường:",
  "环境与账单地址已就绪": "Môi trường và địa chỉ thanh toán đã sẵn sàng",
  "环境已就绪": "Môi trường đã sẵn sàng",
  "玻利维亚": "Bolivia",
  "瑞典": "Thụy Điển",
  "瑞士": "Bản dịch Đức",
  "瑞士移动支付": "Thanh toán di động Thụy Sĩ",
  "生成支付方式失败": "Không thể tạo phương thức thanh toán",
  "生成测试邮箱": "Tạo email thử nghiệm",
  "用于“导入反代平台”阶段。填写 sub2api 地址与管理员 Key 后，注册任务可将已获取 Session/RT 的 GPT 账号导入平台。": "Được sử dụng cho giai đoạn Nhập Nền Tảng Kháng Tạo. Sau khi điền địa chỉ sub2api và khóa quản trị viên, tác vụ đăng ký có thể nhập tài khoản GPT đã nhận Phiên/RT vào nền tảng.",
  "用于账户注册": "Để đăng ký tài khoản",
  "用于邮箱换绑": "Được sử dụng để hoán đổi hộp thư",
  "用途": "Mục đích sử dụng",
  "留空使用已保存 PIN": "Để trống để sử dụng mã PIN đã lưu",
  "留空使用账号代理": "Để trống để sử dụng đại lý tài khoản",
  "留空保持原用途": "Để trống để sử dụng ban đầu",
  "留空保持各代理原国家不变": "Để trống để không thay đổi quốc gia ban đầu của từng đại lý",
  "留空则保持现有凭证": "Để trống để giữ phiếu quà tặng hiện có",
  "登录": "ghi danh",
  "登录刷新": "Làm mới thông tin đăng nhập",
  "登录后修改已有 PIN": "Sửa đổi mã PIN hiện có sau khi đăng nhập",
  "登录密钥": "Khóa đăng nhập",
  "登录密钥已完成": "Đã hoàn tất khóa đăng nhập",
  "登录密钥未全部完成": "Khóa đăng nhập chưa hoàn thành đầy đủ",
  "登录已有号": "Đăng nhập đã có một số",
  "目标分组": "Nhóm đối tượng",
  "目标阶段未完成": "Giai đoạn mục tiêu chưa hoàn thành",
  "直卡任务使用独立运行时与数据文件": "Các tác vụ thẻ trực tiếp sử dụng thời gian chạy độc lập với các tệp dữ liệu",
  "直卡协议": "Thỏa thuận thẻ trực tiếp",
  "直卡协议任务失败": "Tác vụ giao thức thẻ trực tiếp không thành công",
  "直卡协议支付": "Thanh toán thỏa thuận thẻ trực tiếp",
  "直卡绑卡、提链与协议支付任务": "Nhiệm vụ liên kết thẻ trực tiếp, chuỗi và thanh toán giao thức",
  "直接使用协议模式降级时的 Camoufox 无头注册流程，不预执行协议注册请求": "Quy trình đăng ký không đầu Camoufox khi trực tiếp sử dụng chế độ hạ cấp giao thức, không thực hiện trước yêu cầu đăng ký giao thức",
  "短信供应商": "Nhà cung cấp SMS",
  "短信号码": "Mã tín hiệu ngắn",
  "短信号码已释放": "Đã phát hành mã SMS",
  "短信接口": "- SMS brandname",
  "确定": "Xác nhận",
  "确定删除全部 GoPay 账号数据吗？": "Bạn có chắc chắn muốn xóa tất cả dữ liệu tài khoản GoPay không?",
  "确定清空全部号码池吗？": "Bạn có chắc chắn muốn dọn sạch tất cả các hồ bơi không?",
  "确定清空直卡协议账号列表吗？": "Bạn có chắc chắn muốn xóa danh sách các tài khoản thỏa thuận thẻ trực tiếp không?",
  "确认删除该代理？此操作不可撤销。": "Bạn có chắc chắn muốn xóa nhân viên chăm sóc khách hàng này không? Hành động này không thể hoàn tác.",
  "确认删除该手机号？此操作不可撤销。": "Bạn có chắc chắn muốn xóa số điện thoại này không? Hành động này không thể hoàn tác.",
  "确认删除该邮箱分组？": "Bạn có chắc chắn muốn xóa nhóm email này không?",
  "确认删除该邮箱记录？此操作不可撤销。": "Bạn có chắc chắn muốn xóa bản ghi email này không? Hành động này không thể hoàn tác.",
  "确认删除选中的代理？此操作不可撤销。": "Bạn có chắc chắn muốn xóa các proxy đã chọn không? Hành động này không thể hoàn tác.",
  "确认删除选中的手机号？此操作不可撤销。": "Bạn có chắc chắn muốn xóa số điện thoại đã chọn không? Hành động này không thể hoàn tác.",
  "确认删除选中的邮箱记录？此操作不可撤销。": "Bạn có chắc chắn muốn xóa các bản ghi email đã chọn không? Hành động này không thể hoàn tác.",
  "确认并开始支付": "Xác nhận và bắt đầu thanh toán",
  "确认新 PIN": "Xác nhận mã PIN mới",
  "禁用": "Cấm sử dụng",
  "私有资源优先": "Tài nguyên cá nhân trước tiên",
  "科威特": "Kuwait",
  "秘鲁": "bí lỗ",
  "积分数量": "Số điểm",
  "空间名称": "Tên không gian",
  "立陶宛": "Lithuania",
  "第 {page} / {pages} 页": "Trang {page} của {pages}",
  "等待 OTP": "Chờ OTP",
  "等待中": "Đang chờ",
  "等待任务": "Nhiệm vụ đang chờ xử lý",
  "等待任务调度": "Đang chờ lập lịch tác vụ",
  "等待导入账号": "Đang chờ nhập tài khoản",
  "等待执行": "Đang chờ xử lý",
  "等待提链任务": "Đang chờ nhiệm vụ nâng xích",
  "等待提链日志": "Đang chờ nhật ký chuỗi hành trình sản phẩm",
  "等待状态更新": "Đang chờ cập nhật trạng thái",
  "等待续期任务调度": "Đang chờ lập lịch tác vụ gia hạn",
  "等待验证": "Đang chờ xác minh",
  "筛选2FA": "Sàng lọc 2FA",
  "筛选密码": "Lọc mật khẩu",
  "筛选换绑邮箱": "Lọc email thay thế",
  "筛选支付方式": "Lọc phương thức thanh toán",
  "筛选有试用资格的国家": "Các quốc gia sàng lọc đủ điều kiện dùng thử",
  "筛选登录密钥": "Lọc khóa đăng nhập",
  "管理 GoPay 账号": "Quản lý tài khoản GoPay",
  "管理出站代理用途。注册、登录和试用资格检测使用注册/登录代理；Checkout 探测使用账户检测代理；多国家支付方式检测使用支付探测代理。": "Quản lý việc sử dụng proxy gửi đi. Kiểm tra tính đủ điều kiện đăng ký, đăng nhập và dùng thử bằng đại lý đăng ký/đăng nhập; Phát hiện thanh toán bằng đại lý phát hiện tài khoản; phát hiện phương thức thanh toán đa quốc gia bằng đại lý phát hiện thanh toán.",
  "管理出站代理用途。注册任务使用注册/登录代理；试用、Checkout 和支付方式检测使用账户检测代理。": "Quản lý việc sử dụng proxy gửi đi. Nhiệm vụ Đăng ký Sử dụng Đại lý Đăng ký/Đăng nhập; Dùng thử, Thanh toán và Phát hiện Phương thức Thanh toán Sử dụng Đại lý Phát hiện Tài khoản.",
  "管理注册、重新登录与自动取码号码": "Quản lý đăng ký, đăng nhập lại và tự động thu thập số",
  "系统": "Hệ thống",
  "系统邮箱": "Hộp thư hệ thống",
  "系统邮箱池功能未启用，请先启用邮箱池功能": "Tính năng nhóm hộp thư hệ thống chưa được bật, vui lòng bật tính năng nhóm hộp thư trước",
  "系统配置": "Cấu hình hệ thống",
  "系统配置类别": "Danh mục cấu hình hệ thống",
  "累计消费 ": "Chi tiêu tích lũy",
  "线程数": "Số lần thử lại:",
  "终止": "kết thúc",
  "终止中...": "Đang chấm dứt...",
  "终止任务失败": "Không thể chấm dứt nhiệm vụ",
  "绑卡 ": "Thẻ liên kết",
  "绑卡与支付 · US 节点": "Thẻ liên kết và thanh toán · US node",
  "绑定 GoPay 并完成 Midtrans 支付": "Liên kết GoPay và hoàn tất thanh toán Midtrans",
  "绑定 Midtrans": "Bind Midtrans",
  "结束": "kết thúc",
  "结果日志": "Nhật ký kết quả",
  "绕过接码导入反代平台": "Nền tảng chống tạo nhập mã bypass",
  "统一管理支付渠道与相关业务流程。": "Quản lý thống nhất các kênh thanh toán và các quy trình kinh doanh liên quan.",
  "续期": "Gia hạn",
  "续期中...": "Đang gia hạn...",
  "续期失败": "Gia hạn không thành công",
  "续期已中断": "Gia hạn bị gián đoạn",
  "续期成功": "Gia hạn thành công",
  "维护手机号与短信接口": "Duy trì số điện thoại và giao diện SMS",
  "编辑": "HIệu chỉnh",
  "编辑代理": "Chỉnh sửa nhà môi giới",
  "编辑分组名": "Chỉnh sửa tên nhóm",
  "编辑手机号": "Chỉnh sửa số điện thoại",
  "罗马尼亚": "Romania",
  "美国": "nước Mỹ",
  "联动反代配置": "Cấu hình chống tạo liên kết",
  "联动接码配置": "Cấu hình mã liên kết",
  "联动邮箱配置": "Cấu hình hộp thư liên kết",
  "肯尼亚": "Kenya",
  "自动创建邮箱用户": "Tự động tạo người dùng hộp thư",
  "自动注册": "Đăng ký tự động",
  "自动注册 ChatGPT": "Ghi danh tự động vào ChatGPT",
  "自动注册任务已创建": "Đã tạo tác vụ ghi danh tự động",
  "自建域名邮箱": "Email tên miền tự xây dựng",
  "自建域名邮箱已配置": "Hộp thư tên miền tự xây dựng được định cấu hình",
  "自建域名邮箱池": "Nhóm hộp thư miền tự xây dựng",
  "自建手机号池": "Nhóm số điện thoại tự xây dựng",
  "自建邮箱池": "Xây dựng nhóm hộp thư của riêng bạn",
  "芬兰": "Phần Lan",
  "英国": "Vương quốc Liên hiệp Anh và Bắc Ireland",
  "苹果邮箱": "Apple Mail",
  "荷兰": "Hà Lan",
  "荷兰银行支付": "Thanh toán qua ngân hàng Hà Lan",
  "获取": "lấy được",
  "获取RT": "Tải RT",
  "获取列表": "Nhận danh sách",
  "获取邮件": "Nhận thư",
  "获取邮箱": "Nhận email",
  "菲律宾": "Tag- ban- ouă",
  "菲律宾电子钱包": "Ví điện tử Philippines",
  "菲律宾短链": "Chuỗi ngắn Philippines",
  "葡萄牙": "Dựa vào nhận thức",
  "西班牙": "Co dãn",
  "警告": "cảnh cáo",
  "订单": "Đơn hàng",
  "订单 ": "Đơn hàng ",
  "订阅": "đặt",
  "订阅 / 空间": "Đăng ký/Không gian trống",
  "订阅周期": "Thời gian đăng ký",
  "订阅套餐": "Đăng ký gói",
  "订阅检测": "Kiểm tra đăng ký",
  "订阅检测完成：检测 {total} 个，已订阅 {subscribed} 个，未检测到 {notSubscribed} 个，失败 {failed} 个": "Đã hoàn tất phát hiện đăng ký: {total} được phát hiện, {subscribed} đã đăng ký, {notSubscribed} không được phát hiện, {failed} không thành công",
  "订阅检测进度": "Tiến trình kiểm tra đăng ký",
  "认证": "chứng nhận",
  "认证证明失效，正在建立新会话重试": "Bằng chứng xác thực không hợp lệ, thiết lập thử lại phiên mới",
  "设置已保存，将在下一次服务重启后生效": "Cài đặt đã lưu và sẽ có hiệu lực sau khi dịch vụ tiếp theo khởi động lại",
  "设置新 PIN": "Đặt mã PIN mới",
  "试用": "dùng thử",
  "试用检测": "Kiểm tra dùng thử",
  "试用检测进度": "Tiến độ thử nghiệm",
  "试用资格": "Điều kiện thử việc",
  "试用资格与 Checkout 检测完成": "Đủ điều kiện thử việc và hoàn thành kiểm tra thanh toán",
  "试用资格检测完成：检测 {total} 个，有资格 {eligible} 个，无资格 {ineligible} 个，重试 {retried} 个，跳过 {skipped} 个，失败 {failed} 个": "Đã hoàn tất kiểm tra đủ điều kiện dùng thử: {total} được phát hiện, đủ điều kiện {eligible}, không đủ điều kiện {ineligible}, thử lại {retried}, bỏ qua {skipped}, không thành công {failed}",
  "试用资格筛选": "Sàng lọc tính đủ điều kiện thử việc",
  "试用链接": "Liên kết dùng thử",
  "试用：": "dùng thử",
  "该账户当前状态无需测活": "Trạng thái hiện tại của tài khoản không cần kiểm tra",
  "该账户暂无 {field}": "Tài khoản này không có {field}",
  "该账户没有可用 Access Token": "Không có mã thông báo truy cập nào cho tài khoản này",
  "该邮箱凭证信息不完整，无法复制 SK": "Thông tin phiếu quà tặng hộp thư không đầy đủ và không thể sao chép SK",
  "该邮箱分组下存在邮箱账户，请移除后再删除分组": "Có một tài khoản hộp thư trong nhóm hộp thư này, vui lòng xóa tài khoản đó trước khi xóa nhóm",
  "该阶段依赖的配置暂不可用，请先完成对应菜单配置。": "Cấu hình phụ thuộc vào giai đoạn này hiện không khả dụng. Vui lòng hoàn thành cấu hình menu tương ứng trước.",
  "详情": "tình hình rõ ràng",
  "请先勾选需要提链的账户": "Vui lòng kiểm tra tài khoản cần được nâng cấp chuỗi trước",
  "请先启用至少一种邮箱注册方式": "Vui lòng bật ít nhất một phương thức đăng ký email trước",
  "请先在邮箱配置中启用 Remail": "Vui lòng bật Remail trong cấu hình hộp thư của bạn trước",
  "请先填写 Base URL 和 Admin Token": "Vui lòng điền URL cơ sở và mã thông báo quản trị trước",
  "请先填写 Checkout 与 Promotion 代理池": "Vui lòng điền vào ô Checkout (Thanh toán) và Promotion Proxy Pool (Ưu đãi Proxy Pool) trước",
  "请先填写 Checkout 代理池": "Vui lòng điền vào nhóm proxy Thanh toán trước",
  "请先填写 Checkout 代理池并勾选账户": "Vui lòng điền vào nhóm proxy Checkout trước và kiểm tra tài khoản",
  "请先填写 PH Checkout 代理池并勾选账户": "Vui lòng điền vào nhóm đại lý Thanh toán PH trước và kiểm tra tài khoản",
  "请先填写 URL 和 Token": "Vui lòng điền URL và mã thông báo trước",
  "请先填写两个代理池并勾选账户": "Vui lòng điền vào hai nhóm đại lý trước và kiểm tra tài khoản",
  "请先填写或选择邮箱文件": "Vui lòng điền hoặc chọn một tệp email trước",
  "请先新增代理地址，再对启用代理进行批量检测。": "Vui lòng thêm địa chỉ proxy trước khi bật proxy để phát hiện hàng loạt.",
  "请先选择至少一个有效 AT": "Vui lòng chọn ít nhất một hợp LỆ tại lần đầu tiên",
  "请先配置并启用自建域名邮箱": "Vui lòng định cấu hình và bật hộp thư tên miền tự xây dựng trước",
  "请到邮箱配置中手动新增邮箱": "Vui lòng thêm hộp thư theo cách thủ công trong cấu hình hộp thư",
  "请前往接码配置页面启用接码配置": "Vui lòng truy cập trang cấu hình mã kết nối để bật cấu hình mã kết nối",
  "请填写双代理池并完成安全卡片输入": "Vui lòng điền vào nhóm proxy kép và hoàn thành mục nhập thẻ bảo mật",
  "请填写优惠地区代理池并完成安全卡片输入": "Vui lòng điền vào nhóm proxy khu vực thanh toán và hoàn thành mục nhập thẻ bảo mật",
  "请选择账号并填写任意一个代理池": "Vui lòng chọn tài khoản và điền ít nhất một nhóm proxy",
  "请查看下方账户结果": "Vui lòng xem lại kết quả tài khoản bên dưới",
  "请检查新 PIN，两次输入必须一致且不能与原 PIN 相同": "Vui lòng kiểm tra mã PIN mới, hai mục nhập phải nhất quán và không thể giống với mã PIN ban đầu",
  "请点击右上角“导入邮箱”添加自建 Outlook/Hotmail 邮箱池。": "Nhấp vào Nhập hộp thư ở góc trên cùng bên phải để thêm nhóm hộp thư Outlook/Hotmail tự xây dựng.",
  "请至少选择一个探测国家": "Vui lòng chọn ít nhất một quốc gia thăm dò",
  "请至少选择一个账户检测国家": "Vui lòng chọn ít nhất một quốc gia phát hiện tài khoản",
  "请输入 API Key": "Vui lòng nhập Khóa API",
  "请输入 CloudMail PASSWORDS": "Vui lòng nhập mật khẩu CloudMail",
  "请输入 Remail API Key": "Vui lòng nhập Khóa API Remail",
  "请输入 Token": "Vui lòng nhập mã thông báo",
  "请输入自定义备注内容": "Vui lòng nhập nội dung ghi chú tùy chỉnh",
  "请选择本次支付方式探测使用的国家代理": "Vui lòng chọn đại lý quốc gia được sử dụng cho thăm dò phương thức thanh toán này",
  "请选择本次试用资格检测使用的账户检测代理": "Vui lòng chọn đại lý phát hiện tài khoản được sử dụng cho bài kiểm tra trình độ chuyên môn dùng thử này",
  "请选择目标分组": "Vui lòng chọn một nhóm điểm đến",
  "请选择账号": "Vui lòng chọn một tài khoản",
  "请选择账号并填写优惠地区代理池": "Vui lòng chọn một tài khoản và điền vào nhóm đại lý khu vực khuyến mãi",
  "请选择邮箱": "Vui lòng chọn một email",
  "请选择需要导入反代的账户": "Vui lòng chọn một tài khoản để nhập kháng nguyên",
  "请选择需要导出的账号": "Vui lòng chọn một tài khoản để xuất",
  "请选择需要换绑的账户": "Vui lòng chọn một tài khoản để được liên kết",
  "请选择需要探测 Checkout 类型的账户": "Vui lòng chọn một tài khoản yêu cầu loại Probe Checkout",
  "请选择需要探测支付方式的账户": "Vui lòng chọn một tài khoản để tìm kiếm phương thức thanh toán",
  "请选择需要检测订阅的账户": "Vui lòng chọn một tài khoản để kiểm tra đăng ký",
  "请选择需要检测试用资格的账户": "Vui lòng chọn một tài khoản cần được kiểm tra để đủ điều kiện dùng thử",
  "请选择需要测活的账户": "Vui lòng chọn tài khoản cần được kích hoạt",
  "请选择需要添加 LS 的账户": "Vui lòng chọn một tài khoản để thêm LS",
  "请选择需要续期 AT 的账户": "Vui lòng chọn một tài khoản để gia hạn tại",
  "请重新生成": "Vui lòng tạo lại",
  "读取账户凭证": "Đọc thông tin đăng nhập tài khoản",
  "调整日志窗口大小": "Thay đổi kích thước cửa sổ nhật ký",
  "负载因子": "Hệ số tải",
  "账单国家": "Quốc gia thanh toán",
  "账号": "tài khoản",
  "账号ID": "ID tài khoản",
  "账号、号码与任务的实时状态": "Trạng thái thời gian thực của tài khoản, số và tác vụ",
  "账号任务 · ": "Nhiệm vụ của tài khoản ·",
  "账号名前缀": "Tiền tố tên tài khoản",
  "账号已删除": "Đã xóa tài khoản",
  "账号数据已清空": "Đã xóa dữ liệu tài khoản",
  "账户": "Tài khoản ngân hàng số: ……………….",
  "账户 AT": "Tài khoản tại",
  "账户 {email} 的 AT 已更新（AT续期）": "Tại được cập nhật cho tài khoản {email} (lúc gia hạn)",
  "账户 {email} 的 LS 已添加": "LS cho tài khoản {email} đã được thêm",
  "账户 {email} 的 LS 添加失败": "Không thể thêm LS cho tài khoản {email}",
  "账户 {email} 的 RT 已获取": "RT được mua lại cho tài khoản {email}",
  "账户 {email}：Checkout 类型为 {kind}": "Tài khoản {email}: Loại thanh toán là {kind}",
  "账户 {email}：存活": "Tài khoản {email}: Còn sống",
  "账户 {email}：已封禁": "Tài khoản {email}: bị cấm",
  "账户 {email}：已订阅 Plus": "Tài khoản {email}: Đã đăng ký Plus",
  "账户 {email}：探测到 {count} 种支付方式": "Tài khoản {email}: {count} phương thức thanh toán được phát hiện",
  "账户 {email}：未检测到订阅成功邮件": "Tài khoản {email}: Không phát hiện thấy email đăng ký thành công",
  "账户 {email}：订阅检测失败": "Tài khoản {email}: Phát hiện đăng ký không thành công",
  "账户 {email}：试用资格检测失败": "Tài khoản {email}: Kiểm tra tính đủ điều kiện dùng thử không thành công",
  "账户 {email}：试用资格检测完成": "Tài khoản {email}: Đã hoàn tất kiểm tra tính đủ điều kiện dùng thử",
  "账户列表已刷新": "Đã làm mới danh sách tài khoản",
  "账户定时测活": "Kích hoạt tài khoản theo thời gian",
  "账户已存在完整 LS，已跳过": "Tài khoản đã tồn tại LS đầy đủ, đã bỏ qua",
  "账户已封禁": "Tài khoản bị cấm",
  "账户提链详情": "Chi tiết chuỗi tài khoản",
  "账户检测": "Phát hiện tài khoản",
  "账户注册进度": "Tiến độ đăng ký tài khoản",
  "账户测活失败": "Kích hoạt tài khoản không thành công",
  "账户管理": "Quản lý tài khoản",
  "账户管理日志": "Nhật ký quản lý tài khoản",
  "购买邮箱": "Email mua hàng",
  "资格与 Checkout 检测完成": "Đủ điều kiện và hoàn tất kiểm tra Thanh toán",
  "越南": "Việt Nam",
  "越南 MOMO 钱包 OAICS 授权链接批量提取": "Ví Momo Việt Nam OAICS Liên kết được ủy quyền Rút tiền hàng loạt",
  "越南代理池": "Quỹ đại lý Việt Nam",
  "越南电子钱包": "Ví điện tử Việt Nam",
  "身份提升": "Cải thiện trạng thái",
  "输入分组名后回车": "Nhập tên nhóm và nhập",
  "输入支付 OTP": "Nhập OTP thanh toán",
  "迁移到分组": "Di chuyển vào nhóm",
  "过程日志": "Nhật ký quy trình",
  "运行中": "Đang chạy",
  "运行总览": "Tổng quan về hoạt động",
  "进度": "Tiến độ",
  "进行中": "Đang tiến hành",
  "远端代理": "Proxy từ xa",
  "选填": "Tùy chọn",
  "选择": "lựa chọn",
  "选择全部有效 AT": "Chọn tất cả các AT hợp lệ",
  "选择执行方式": "Chọn phương thức thực hiện",
  "选择探测国家": "Chọn quốc gia khám phá",
  "选择支付任务": "Chọn một nhiệm vụ thanh toán",
  "选择文件": "Chọn tập tin...",
  "选择注册身份": "Chọn danh tính đã đăng ký",
  "选择注册阶段": "Chọn giai đoạn ghi danh",
  "选择试用检测国家": "Chọn quốc gia thử nghiệm thử nghiệm",
  "选择账户并开始任务后显示逐账户进度": "Hiển thị tiến độ theo từng tài khoản sau khi chọn tài khoản và bắt đầu một nhiệm vụ",
  "通过 CloudMail/CF Worker API 生成多个域名邮箱并收取验证码。": "Tạo nhiều địa chỉ email tên miền và nhận mã xác minh thông qua API CloudMail/CF Worker.",
  "通过供应商编号从 LubanSMS 获取一次性手机号并自动轮询验证码。": "Nhận số điện thoại một lần từ LubanSMS thông qua số nhà cung cấp và tự động thăm dò mã xác minh.",
  "通过邮箱专属取码 URL 查询最新邮件，单次响应最长约 30 秒": "Truy vấn thư mới nhất thông qua mã duy nhất lấy URL của hộp thư và thời gian phản hồi tối đa là khoảng 30 giây.",
  "遇到挑战时保存协议认证 Cookie 与当前步骤，由 Camoufox 从断点继续，不重新执行已完成的注册流程": "Lưu cookie xác thực giao thức và các bước hiện tại khi bị thử thách, tiếp tục từ điểm ngắt bằng Camoufox mà không cần thực hiện lại quy trình đăng ký đã hoàn tất",
  "遇到挑战时由完整后台浏览器接管注册流程": "Một trình duyệt nền đầy đủ sẽ tiếp quản quá trình đăng ký khi bị thách thức",
  "遇到验证时会在当前支付代理下打开 Midtrans 页面，获取动态参数、Cookie 与一次性令牌；未触发验证时不会启动浏览器。": "Khi gặp phải xác thực, trang Midtrans được mở dưới đại lý thanh toán hiện tại để lấy các thông số động, cookie và mã thông báo một lần; trình duyệt không được khởi chạy khi xác thực không được kích hoạt.",
  "邮件内容": "Nội dung email",
  "邮件列表": "Danh sách gửi thư",
  "邮件查询": "Truy vấn thư",
  "邮箱": "email",
  "邮箱 / 邮箱----密码 / 邮箱----收码URL / 可选2FA": "Hộp thư/Email - Mật khẩu/Email - URL nhận/2FA tùy chọn",
  "邮箱凭证已就绪": "Thông tin đăng nhập email đã sẵn sàng",
  "邮箱分组删除成功": "Đã xóa thành công nhóm hộp thư",
  "邮箱分组名称修改成功": "Đã thay đổi tên nhóm hộp thư thành công",
  "邮箱分组名称已存在": "Tên nhóm hộp thư đã tồn tại",
  "邮箱分组新建成功": "Đã tạo nhóm hộp thư thành công",
  "邮箱列表": "Danh sách gửi thư",
  "邮箱前缀长度": "Độ dài tiền tố hộp thư",
  "邮箱名": "Tên email",
  "邮箱后缀（可选）": "Hậu tố email (không bắt buộc)",
  "邮箱域名（每行一个）": "Tên miền email (mỗi dòng một tên)",
  "邮箱总数": "Tổng số hộp thư",
  "邮箱换绑": "Thay thế hộp thư",
  "邮箱换绑失败": "Hoán đổi hộp thư không thành công",
  "邮箱数量": "Số lượng email",
  "邮箱类型": "Loại email",
  "邮箱账户": "Tài khoản email",
  "邮箱配置": "Cấu hình email",
  "邮箱验证码提交后出现交互式验证，请在当前可视浏览器中完成": "Có xác minh tương tác sau khi mã xác minh email được gửi, vui lòng hoàn thành trong trình duyệt trực quan hiện tại",
  "部分已选 AT 已过期或失效，请确认列表后重试": "Một số AT đã chọn đã hết hạn hoặc không hợp lệ, vui lòng xác nhận danh sách và thử lại",
  "配置国家代理池后，输入 BA 链接和手机号创建任务": "Sau khi định cấu hình nhóm tác nhân quốc gia, hãy nhập liên kết BA và số điện thoại để tạo tác vụ",
  "配置已保存，后续新任务立即生效": "Cấu hình đã được lưu, các tác vụ mới tiếp theo sẽ có hiệu lực ngay lập tức",
  "配置未更改": "Cấu hình không thay đổi",
  "释放号码": "Số phát hành",
  "释放后将无法自动接收付款 OTP，确定继续吗？": "Sau khi phát hành, bạn sẽ không thể tự động nhận OTP thanh toán, bạn có chắc chắn muốn tiếp tục không?",
  "重新登录": "Đăng nhập lại",
  "重新登录任务已创建": "Đã tạo tác vụ đăng nhập lại",
  "金额": "Số tiền",
  "链接已过期": "Liên kết đã hết hạn",
  "错误": "Lỗi",
  "阶段": "Giai",
  "阿曼": "Ôman",
  "阿根廷": "Bản dịch Tây Ban Nha",
  "阿联酋": "Các Tiểu Vương Quốc Ả Rập Thống Nhất",
  "隐藏提链日志": "Ẩn nhật ký nâng xích",
  "隐藏日志": "Ẩn nhật ký",
  "隐藏明文": "Ẩn văn bản rõ ràng",
  "隐藏账户管理日志": "Ẩn nhật ký quản lý tài khoản",
  "需二验": "Cần thực hiện hai xét nghiệm",
  "韩国": "Korea",
  "韩国 Nicepay 跳转": "Bước nhảy Nicepay của Hàn Quốc",
  "页面未找到可用的验证码提交控件，使用兼容接口提交": "Trang không tìm thấy kiểm soát gửi CAPTCHA khả dụng, hãy sử dụng giao diện tương thích để gửi",
  "项目": "Danh mục",
  "项目 / 产品": "Dự án/Sản phẩm",
  "预留身份，后续接入 Google 账号": "Đặt trước danh tính, quyền truy cập tiếp theo vào tài khoản Google",
  "预留身份，后续接入 Microsoft 账号": "Đặt trước danh tính, quyền truy cập tiếp theo vào tài khoản Microsoft",
  "风控拒绝": "Từ chối kiểm soát rủi ro",
  "马来西亚": "Malaysia",
  "马耳他": "Đỏ tươi",
  "验证 OTP": "Xác minh OTP",
  "验证 PIN": "Xác minh mã PIN",
  "验证并修改": "Xác thực và sửa đổi",
  "验证码": "mã xác minh",
  "验证码发送至 ": "Mã xác minh đã được gửi đến",
  "验证码已提交": "Đã gửi mã xác minh",
  "验证码服务": "Dịch vụ CAPTCHA",
  "验证码查询入口：https://icloud.xbovo.online/code": "Cổng thông tin yêu cầu mã xác minh: https://icloud.xbovo.online/code",
  "验证策略：自动识别 Outlook/Hotmail Graph API 或 IMAP/XOAUTH2 并读取验证码": "Chính sách xác thực: Tự động xác định API đồ thị Outlook/Hotmail hoặc IMAP/XOAUTH2 và đọc CAPTCHA",
  "默认关闭：只有 ChatGPT 官方注册/登录使用代理池；邮箱读取、接码、试用和其他外部 API 由服务器直接访问。勾选后，整个注册任务统一使用代理池出口。": "Tắt mặc định: Chỉ các đăng ký/thông tin đăng nhập chính thức của ChatGPT sử dụng nhóm proxy; đọc hộp thư, kết nối, dùng thử và các API bên ngoài khác được truy cập trực tiếp bởi máy chủ. Khi được chọn, việc thoát nhóm proxy được sử dụng thống nhất cho toàn bộ tác vụ đăng ký.",
  "默认分组": "Nhóm mặc định",
  "默认分组不能删除": "Không thể xóa nhóm mặc định",
  "默认国家": "Quốc gia mặc định",
  "默认服务": "Dịch vụ mặc định:",
  "，共 ": "cũng có",
  "；注册机将使用服务器系统出口": "; Nhà đăng ký sẽ sử dụng lối ra hệ thống máy chủ",
};
